ALTER TABLE `cus_customer_master`
  ADD COLUMN `contact_phone` varchar(64) DEFAULT NULL COMMENT 'CRM联系电话副本' AFTER `temporary_reason`,
  ADD COLUMN `contact_email` varchar(128) DEFAULT NULL COMMENT 'CRM邮箱副本' AFTER `contact_phone`,
  ADD COLUMN `department_code` varchar(64) DEFAULT NULL COMMENT '所属办事处统一部门编码' AFTER `contact_email`,
  ADD COLUMN `department_name` varchar(128) DEFAULT NULL COMMENT '所属办事处部门名称快照' AFTER `department_code`,
  ADD COLUMN `market_code` varchar(64) DEFAULT NULL COMMENT '市场部编码' AFTER `department_name`,
  ADD COLUMN `market_name` varchar(128) DEFAULT NULL COMMENT '市场部名称' AFTER `market_code`,
  ADD COLUMN `system_code` varchar(64) DEFAULT NULL COMMENT '系统部编码' AFTER `market_name`,
  ADD COLUMN `system_name` varchar(128) DEFAULT NULL COMMENT '系统部名称' AFTER `system_code`,
  ADD COLUMN `expend_code` varchar(64) DEFAULT NULL COMMENT '拓展部编码' AFTER `system_name`,
  ADD COLUMN `expend_name` varchar(128) DEFAULT NULL COMMENT '拓展部名称' AFTER `expend_code`,
  ADD COLUMN `industry_code` varchar(64) DEFAULT NULL COMMENT '子行业编码' AFTER `expend_name`,
  ADD COLUMN `industry_name` varchar(128) DEFAULT NULL COMMENT '子行业名称' AFTER `industry_code`,
  ADD KEY `idx_cus_customer_master_department` (`tenant_id`, `department_code`),
  ADD KEY `idx_cus_customer_master_classification` (`tenant_id`, `market_code`, `system_code`, `expend_code`, `industry_code`);

CREATE TABLE `cus_market_relation` (
  `id` bigint NOT NULL,
  `market_code` varchar(64) NOT NULL,
  `market_name` varchar(128) NOT NULL,
  `system_code` varchar(64) NOT NULL,
  `system_name` varchar(128) NOT NULL,
  `expend_code` varchar(64) NOT NULL,
  `expend_name` varchar(128) NOT NULL,
  `industry_code` varchar(64) NOT NULL,
  `industry_name` varchar(128) NOT NULL,
  `mapping_status` varchar(32) NOT NULL,
  `source_version` varchar(64) NOT NULL,
  `data_as_of` datetime NOT NULL,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cus_market_relation_codes` (`tenant_id`, `market_code`, `system_code`, `expend_code`, `industry_code`),
  KEY `idx_cus_market_relation_market` (`tenant_id`, `market_code`, `mapping_status`),
  KEY `idx_cus_market_relation_system` (`tenant_id`, `market_code`, `system_code`, `mapping_status`),
  KEY `idx_cus_market_relation_expend` (`tenant_id`, `market_code`, `system_code`, `expend_code`, `mapping_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CUS市场行业四级组合目录';

CREATE TABLE `cus_customer_scope_slice` (
  `id` bigint NOT NULL,
  `subject_type` varchar(16) NOT NULL,
  `subject_id` bigint NOT NULL,
  `department_mode` varchar(16) NOT NULL,
  `department_codes` text DEFAULT NULL,
  `market_mode` varchar(16) NOT NULL,
  `market_codes` text DEFAULT NULL,
  `system_mode` varchar(16) NOT NULL,
  `system_codes` text DEFAULT NULL,
  `expend_mode` varchar(16) NOT NULL,
  `expend_codes` text DEFAULT NULL,
  `industry_mode` varchar(16) NOT NULL,
  `industry_codes` text DEFAULT NULL,
  `effective_from` datetime NOT NULL,
  `effective_to` datetime DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_cus_customer_scope_subject` (`tenant_id`, `subject_type`, `subject_id`, `status`, `effective_from`, `effective_to`),
  CONSTRAINT `ck_cus_customer_scope_subject` CHECK (`subject_type` IN ('USER', 'ROLE')),
  CONSTRAINT `ck_cus_customer_scope_department_mode` CHECK (`department_mode` IN ('ALL', 'SELECTED', 'NONE')),
  CONSTRAINT `ck_cus_customer_scope_market_mode` CHECK (`market_mode` IN ('ALL', 'SELECTED', 'NONE')),
  CONSTRAINT `ck_cus_customer_scope_system_mode` CHECK (`system_mode` IN ('ALL', 'SELECTED', 'NONE')),
  CONSTRAINT `ck_cus_customer_scope_expend_mode` CHECK (`expend_mode` IN ('ALL', 'SELECTED', 'NONE')),
  CONSTRAINT `ck_cus_customer_scope_industry_mode` CHECK (`industry_mode` IN ('ALL', 'SELECTED', 'NONE')),
  CONSTRAINT `ck_cus_customer_scope_interval` CHECK (`effective_to` IS NULL OR `effective_to` > `effective_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CUS客户复选权限切片';
