-- ====================================================================
-- T-V1-ENG-A / T-V1-ENG-B / T-V1-ENG-C
-- 工程实施域：工勘、需求、接口规划、实施方案、方案审核、资源就绪、
-- 到货签收、硬件安装、配置调试、业务联调、实施问题、交付件归集
-- 注：超过 varchar(500) 的长文本字段统一使用 TEXT，避免 MySQL 行大小 65535 限制。
-- ====================================================================

-- 1. 现场工勘主表（FR-ENG-001）
CREATE TABLE pms_eng_site_survey (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '工勘编码，项目内唯一',
  name varchar(128) NOT NULL COMMENT '工勘名称',
  survey_date date DEFAULT NULL COMMENT '工勘日期',
  surveyor_user_id bigint DEFAULT NULL COMMENT '工勘责任人',
  location varchar(255) DEFAULT NULL COMMENT '工勘地点',
  power_supply varchar(500) DEFAULT NULL COMMENT '供电条件',
  cabinet varchar(500) DEFAULT NULL COMMENT '机柜条件',
  network_port varchar(500) DEFAULT NULL COMMENT '网口条件',
  fiber varchar(500) DEFAULT NULL COMMENT '光纤条件',
  module varchar(500) DEFAULT NULL COMMENT '模块条件',
  cable varchar(500) DEFAULT NULL COMMENT '线缆条件',
  ground varchar(500) DEFAULT NULL COMMENT '接地条件',
  construction_resource varchar(500) DEFAULT NULL COMMENT '施工资源条件',
  conclusion varchar(500) DEFAULT NULL COMMENT '工勘结论',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0草稿 1已确认 2已驳回 3已归档',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_site_survey_code (project_id, code),
  KEY idx_pms_eng_site_survey_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='现场工勘主表';

-- 2. 需求分析主表（FR-ENG-004）
CREATE TABLE pms_eng_requirement (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '需求编码，项目内唯一',
  name varchar(128) NOT NULL COMMENT '需求名称',
  requirement_type varchar(32) NOT NULL DEFAULT 'BUSINESS' COMMENT 'BUSINESS 业务需求 / INTERFACE 接口规划',
  background text DEFAULT NULL COMMENT '项目背景目标',
  topology text DEFAULT NULL COMMENT '拓扑',
  transmission text DEFAULT NULL COMMENT '传输',
  traffic text DEFAULT NULL COMMENT '流量',
  business text DEFAULT NULL COMMENT '业务',
  ip_plan text DEFAULT NULL COMMENT 'IP 规划',
  redundancy text DEFAULT NULL COMMENT '冗余',
  protection text DEFAULT NULL COMMENT '防护',
  o_and_m text DEFAULT NULL COMMENT '运维',
  log_retention text DEFAULT NULL COMMENT '日志留存',
  interface_content text DEFAULT NULL COMMENT '接口关系内容（type=INTERFACE 时使用）',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0草稿 1已提交 2已生效 3已归档',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_requirement_code (project_id, code),
  KEY idx_pms_eng_requirement_project (project_id),
  KEY idx_pms_eng_requirement_type (project_id, requirement_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='需求分析与接口规划';

-- 3. 实施方案主表（FR-ENG-011 / FR-ENG-013）
CREATE TABLE pms_eng_solution (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '方案编码，项目内唯一',
  name varchar(128) NOT NULL COMMENT '方案名称',
  solution_type varchar(32) DEFAULT 'IMPLEMENTATION' COMMENT '方案类型',
  background text DEFAULT NULL COMMENT '背景',
  target text DEFAULT NULL COMMENT '目标',
  team text DEFAULT NULL COMMENT '团队',
  inventory text DEFAULT NULL COMMENT '清单',
  plan text DEFAULT NULL COMMENT '计划',
  topology text DEFAULT NULL COMMENT '拓扑',
  interface_plan text DEFAULT NULL COMMENT '接口',
  ip_plan text DEFAULT NULL COMMENT 'IP',
  version_label varchar(64) DEFAULT NULL COMMENT '版本标签',
  script text DEFAULT NULL COMMENT '脚本',
  quality text DEFAULT NULL COMMENT '质量',
  risk text DEFAULT NULL COMMENT '风险',
  o_and_m text DEFAULT NULL COMMENT '运维',
  review_level tinyint NOT NULL DEFAULT 0 COMMENT '审核级别 0 普通 1 重大',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0草稿 1已提交 2审批中 3已通过 4已驳回 5已撤回 6已终止',
  approved_by bigint DEFAULT NULL COMMENT '审核人',
  approved_time datetime DEFAULT NULL COMMENT '审核时间',
  approval_opinion varchar(1000) DEFAULT NULL COMMENT '审核意见',
  baseline_version int DEFAULT NULL COMMENT '基线版本号（审核通过后冻结）',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_solution_code (project_id, code),
  KEY idx_pms_eng_solution_project (project_id),
  KEY idx_pms_eng_solution_status (project_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实施方案';

-- 4. 方案来源追溯（FR-ENG-013 前序数据带入）
CREATE TABLE pms_eng_solution_source (
  id bigint NOT NULL AUTO_INCREMENT,
  solution_id bigint NOT NULL COMMENT '方案编号',
  source_type varchar(32) NOT NULL COMMENT 'SURVEY 工勘 / REQUIREMENT 需求',
  source_id bigint NOT NULL COMMENT '来源业务编号',
  source_code varchar(64) DEFAULT NULL COMMENT '来源业务编码',
  source_snapshot text DEFAULT NULL COMMENT '带入时的来源快照（JSON）',
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_solution_source (solution_id, source_type, source_id),
  KEY idx_pms_eng_solution_source_solution (solution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='方案来源追溯';

-- 5. 资源与备件就绪（FR-ENG-018）
CREATE TABLE pms_eng_resource_ready (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '就绪编码，项目内唯一',
  name varchar(128) NOT NULL COMMENT '资源名称',
  resource_type varchar(32) NOT NULL COMMENT 'PEOPLE 备件 / SPARE 物料 / TOOL 工具 / TEST_ENV 测试环境 / WINDOW 时间窗口 / APPROVAL 客户批准',
  equipment_id bigint DEFAULT NULL COMMENT '关联设备编号',
  quantity int DEFAULT NULL COMMENT '数量',
  ready_status tinyint NOT NULL DEFAULT 0 COMMENT '0未就绪 1已就绪 2异常',
  ready_time datetime DEFAULT NULL COMMENT '就绪时间',
  ready_user_id bigint DEFAULT NULL COMMENT '就绪确认人',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_resource_ready_code (project_id, code),
  KEY idx_pms_eng_resource_ready_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资源与备件就绪';

-- 6. 到货签收（FR-ENG-021）
CREATE TABLE pms_eng_arrival (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '签收编码，项目内唯一',
  arrival_time datetime NOT NULL COMMENT '到货时间',
  receiver_user_id bigint DEFAULT NULL COMMENT '签收人',
  equipment_id bigint DEFAULT NULL COMMENT '关联设备编号',
  quantity int NOT NULL DEFAULT 1 COMMENT '到货数量',
  inspection_result varchar(1000) DEFAULT NULL COMMENT '外观与清单检查结果',
  exception_record varchar(1000) DEFAULT NULL COMMENT '异常记录',
  attachment_url varchar(500) DEFAULT NULL COMMENT '签收单附件',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待签收 1已签收 2异常',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_arrival_code (project_id, code),
  KEY idx_pms_eng_arrival_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='到货签收';

-- 7. 硬件安装记录（FR-ENG-022）
CREATE TABLE pms_eng_installation (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '安装编码，项目内唯一',
  equipment_id bigint NOT NULL COMMENT '设备编号',
  install_location varchar(255) DEFAULT NULL COMMENT '安装位置',
  install_time datetime DEFAULT NULL COMMENT '安装时间',
  installer_user_id bigint DEFAULT NULL COMMENT '安装人',
  environment_check varchar(1000) DEFAULT NULL COMMENT '环境检查',
  spec_check varchar(1000) DEFAULT NULL COMMENT '安装规范检查',
  photo_url varchar(500) DEFAULT NULL COMMENT '安装照片',
  result varchar(1000) DEFAULT NULL COMMENT '安装结果',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待安装 1进行中 2已完成 3异常',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_installation_code (project_id, code),
  KEY idx_pms_eng_installation_project (project_id),
  KEY idx_pms_eng_installation_equipment (equipment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='硬件安装记录';

-- 8. 配置调试记录（FR-ENG-023）
CREATE TABLE pms_eng_configuration (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '配置编码，项目内唯一',
  equipment_id bigint NOT NULL COMMENT '设备编号',
  config_log_url varchar(500) DEFAULT NULL COMMENT '配置Log文件',
  debug_result text DEFAULT NULL COMMENT '调试结果',
  debugger_user_id bigint DEFAULT NULL COMMENT '调试人',
  debug_time datetime DEFAULT NULL COMMENT '调试时间',
  config_snapshot text DEFAULT NULL COMMENT '配置档案快照',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待调试 1进行中 2已完成 3异常',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_configuration_code (project_id, code),
  KEY idx_pms_eng_configuration_project (project_id),
  KEY idx_pms_eng_configuration_equipment (equipment_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='配置调试记录';

-- 9. 业务联调记录（FR-ENG-024）
CREATE TABLE pms_eng_joint_test (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '联调编码，项目内唯一',
  test_case varchar(500) NOT NULL COMMENT '联调用例',
  equipment_id bigint DEFAULT NULL COMMENT '关联设备编号',
  participants varchar(500) DEFAULT NULL COMMENT '参与方',
  test_time datetime DEFAULT NULL COMMENT '联调时间',
  tester_user_id bigint DEFAULT NULL COMMENT '联调人',
  result text DEFAULT NULL COMMENT '联调结果',
  exception_record text DEFAULT NULL COMMENT '异常记录',
  evidence_url varchar(500) DEFAULT NULL COMMENT '证据附件',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待联调 1进行中 2通过 3失败',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_joint_test_code (project_id, code),
  KEY idx_pms_eng_joint_test_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务联调记录';

-- 10. 实施问题与整改（FR-ENG-026）
CREATE TABLE pms_eng_issue (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  code varchar(64) NOT NULL COMMENT '问题编码，项目内唯一',
  name varchar(255) NOT NULL COMMENT '问题名称',
  description text DEFAULT NULL COMMENT '问题描述',
  source varchar(32) DEFAULT 'INSTALLATION' COMMENT '来源 INSTALLATION 安装 / CONFIGURATION 配置 / JOINT_TEST 联调 / OTHER 其他',
  severity tinyint NOT NULL DEFAULT 1 COMMENT '严重等级 1低 2中 3高',
  owner_user_id bigint DEFAULT NULL COMMENT '责任人',
  deadline datetime DEFAULT NULL COMMENT '整改时限',
  solution text DEFAULT NULL COMMENT '整改方案',
  verification_standard varchar(1000) DEFAULT NULL COMMENT '验证标准',
  verify_result text DEFAULT NULL COMMENT '复测结果',
  verified_by bigint DEFAULT NULL COMMENT '验证人',
  verified_time datetime DEFAULT NULL COMMENT '验证时间',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待处理 1整改中 2待验证 3已关闭 4已挂起',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_issue_code (project_id, code),
  KEY idx_pms_eng_issue_project (project_id),
  KEY idx_pms_eng_issue_status (project_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='实施问题与整改';

-- 11. 阶段交付件归集（FR-ENG-027）
CREATE TABLE pms_eng_deliverable (
  id bigint NOT NULL AUTO_INCREMENT,
  project_id bigint NOT NULL COMMENT '所属项目编号',
  phase_id bigint DEFAULT NULL COMMENT '阶段编号',
  code varchar(64) NOT NULL COMMENT '交付件编码，项目内唯一',
  name varchar(255) NOT NULL COMMENT '交付件名称',
  deliverable_type varchar(32) NOT NULL COMMENT '类型 DAILY 日报 / RECEIPT 签收单 / SERVICE 服务单 / COMPLETION 完工证明 / TEST 测试记录 / CONFIG 配置档案',
  source_type varchar(32) DEFAULT NULL COMMENT '来源业务类型',
  source_id bigint DEFAULT NULL COMMENT '来源业务编号',
  file_url varchar(500) DEFAULT NULL COMMENT '文件地址',
  file_size bigint DEFAULT NULL COMMENT '文件大小',
  file_checksum varchar(128) DEFAULT NULL COMMENT '文件校验值',
  status tinyint NOT NULL DEFAULT 0 COMMENT '0待归集 1已归集 2已作废',
  archived_time datetime DEFAULT NULL COMMENT '归集时间',
  archived_by bigint DEFAULT NULL COMMENT '归集人',
  remark varchar(500) DEFAULT NULL,
  version int NOT NULL DEFAULT 0,
  creator varchar(64) DEFAULT '',
  create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater varchar(64) DEFAULT '',
  update_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted bit(1) NOT NULL DEFAULT b'0',
  tenant_id bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uk_pms_eng_deliverable_code (project_id, code),
  KEY idx_pms_eng_deliverable_project (project_id),
  KEY idx_pms_eng_deliverable_phase (phase_id),
  KEY idx_pms_eng_deliverable_source (source_type, source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='阶段交付件归集';
