CREATE TABLE `ast_device_shipment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '发货记录编号',
  `device_sn` varchar(100) NOT NULL COMMENT '设备序列号',
  `shipment_time` datetime(3) DEFAULT NULL COMMENT '发货时间',
  `package_no` varchar(64) DEFAULT NULL COMMENT '装箱单编号',
  `contract_no` varchar(64) DEFAULT NULL COMMENT '合同编号',
  `event_type` varchar(32) NOT NULL COMMENT '发货事件类型',
  `warranty_start_date` date DEFAULT NULL COMMENT '发货约定维保开始日期',
  `warranty_months` int unsigned DEFAULT NULL COMMENT '发货约定维保月数',
  `rma_no` varchar(128) DEFAULT NULL COMMENT 'RMA编号',
  `related_device_sn` varchar(100) DEFAULT NULL COMMENT '关联设备序列号',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_shipment_source` (`tenant_id`, `source_system`, `source_key`),
  KEY `idx_ast_device_shipment_device` (`tenant_id`, `device_sn`, `shipment_time`, `id`),
  KEY `idx_ast_device_shipment_package` (`tenant_id`, `package_no`, `device_sn`),
  KEY `idx_ast_device_shipment_contract` (`tenant_id`, `contract_no`, `device_sn`),
  CONSTRAINT `fk_ast_device_shipment_device`
    FOREIGN KEY (`tenant_id`, `device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`),
  CONSTRAINT `fk_ast_device_shipment_related_device`
    FOREIGN KEY (`tenant_id`, `related_device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备发货记录';

CREATE TABLE `ast_device_factory_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '出厂版本编号',
  `device_sn` varchar(100) NOT NULL COMMENT '设备序列号',
  `conp_version` varchar(255) DEFAULT NULL COMMENT 'CONP原始版本',
  `conp_type` varchar(100) DEFAULT NULL COMMENT 'CONP类型',
  `conp_series` varchar(100) DEFAULT NULL COMMENT 'CONP系列',
  `conp_mark` varchar(255) DEFAULT NULL COMMENT 'CONP版本掩码',
  `boot_version` varchar(255) DEFAULT NULL COMMENT 'BOOT版本',
  `cpld_version` varchar(255) DEFAULT NULL COMMENT 'CPLD版本',
  `pcb_version` varchar(255) DEFAULT NULL COMMENT 'PCB版本',
  `customized` bit(1) DEFAULT NULL COMMENT '是否定制版本',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_factory_version_device` (`tenant_id`, `device_sn`),
  UNIQUE KEY `uk_ast_device_factory_version_source` (`tenant_id`, `source_system`, `source_key`),
  CONSTRAINT `fk_ast_device_factory_version_device`
    FOREIGN KEY (`tenant_id`, `device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备出厂软件版本';

CREATE TABLE `ast_product_official_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '官网产品信息编号',
  `product_code` varchar(64) NOT NULL COMMENT '产品编码',
  `product_model` varchar(128) DEFAULT NULL COMMENT '产品型号',
  `product_name` varchar(128) DEFAULT NULL COMMENT '产品名称',
  `product_desc` text DEFAULT NULL COMMENT '产品描述',
  `technical_spec` text DEFAULT NULL COMMENT '技术规格',
  `document_id` bigint DEFAULT NULL COMMENT '官方文档稳定引用',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_product_official_info_source` (`tenant_id`, `source_system`, `source_key`),
  KEY `idx_ast_product_official_info_product` (`tenant_id`, `product_code`, `product_model`, `deleted`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST官网产品信息副本';

CREATE TABLE `ast_product_official_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '官网版本编号',
  `product_code` varchar(64) NOT NULL COMMENT '产品编码',
  `product_model` varchar(128) DEFAULT NULL COMMENT '产品型号',
  `conp_version` varchar(255) DEFAULT NULL COMMENT 'CONP原始版本',
  `conp_type` varchar(100) DEFAULT NULL COMMENT 'CONP类型',
  `conp_series` varchar(100) DEFAULT NULL COMMENT 'CONP系列',
  `conp_mark` varchar(255) DEFAULT NULL COMMENT 'CONP版本掩码',
  `boot_version` varchar(255) DEFAULT NULL COMMENT 'BOOT版本',
  `cpld_version` varchar(255) DEFAULT NULL COMMENT 'CPLD版本',
  `pcb_version` varchar(255) DEFAULT NULL COMMENT 'PCB版本',
  `customized` bit(1) DEFAULT NULL COMMENT '是否定制版本',
  `release_date` date DEFAULT NULL COMMENT '版本发布日期',
  `version_desc` varchar(1000) DEFAULT NULL COMMENT '版本说明',
  `document_id` bigint DEFAULT NULL COMMENT '官方文档稳定引用',
  `status` varchar(32) NOT NULL COMMENT '状态',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_product_official_version_source` (`tenant_id`, `source_system`, `source_key`),
  KEY `idx_ast_product_official_version_product` (`tenant_id`, `product_code`, `product_model`, `status`, `release_date`, `id`),
  KEY `idx_ast_product_official_version_conp` (`tenant_id`, `product_code`, `conp_version`, `id`),
  KEY `idx_ast_product_official_version_conp_parse` (`tenant_id`, `product_code`, `conp_type`, `conp_series`, `conp_mark`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST官网软件版本副本';

CREATE TABLE `ast_device_network_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '当前在网版本编号',
  `device_sn` varchar(100) NOT NULL COMMENT '设备序列号',
  `conp_version` varchar(255) DEFAULT NULL COMMENT 'CONP原始版本',
  `conp_type` varchar(100) DEFAULT NULL COMMENT 'CONP类型',
  `conp_series` varchar(100) DEFAULT NULL COMMENT 'CONP系列',
  `conp_mark` varchar(255) DEFAULT NULL COMMENT 'CONP版本掩码',
  `boot_version` varchar(255) DEFAULT NULL COMMENT 'BOOT版本',
  `cpld_version` varchar(255) DEFAULT NULL COMMENT 'CPLD版本',
  `pcb_version` varchar(255) DEFAULT NULL COMMENT 'PCB版本',
  `customized` bit(1) DEFAULT NULL COMMENT '是否定制版本',
  `release_date` date DEFAULT NULL COMMENT '版本发布日期',
  `version_desc` varchar(1000) DEFAULT NULL COMMENT '版本说明',
  `effective_from` datetime(3) DEFAULT NULL COMMENT '设备版本生效时间',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_network_version_device` (`tenant_id`, `device_sn`),
  UNIQUE KEY `uk_ast_device_network_version_source` (`tenant_id`, `source_system`, `source_key`),
  KEY `idx_ast_device_network_version_conp` (`tenant_id`, `conp_version`, `device_sn`),
  KEY `idx_ast_device_network_version_conp_parse` (`tenant_id`, `conp_type`, `conp_series`, `conp_mark`, `device_sn`),
  CONSTRAINT `fk_ast_device_network_version_device`
    FOREIGN KEY (`tenant_id`, `device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备当前在网软件版本';

CREATE TABLE `ast_device_network_version_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '在网版本事件编号',
  `device_sn` varchar(100) DEFAULT NULL COMMENT '已映射设备序列号',
  `source_device_key` varchar(128) NOT NULL COMMENT '来源设备键',
  `source_event_key` varchar(128) NOT NULL COMMENT '来源事件键',
  `conp_version` varchar(255) DEFAULT NULL COMMENT 'CONP原始版本',
  `conp_type` varchar(100) DEFAULT NULL COMMENT 'CONP类型',
  `conp_series` varchar(100) DEFAULT NULL COMMENT 'CONP系列',
  `conp_mark` varchar(255) DEFAULT NULL COMMENT 'CONP版本掩码',
  `boot_version` varchar(255) DEFAULT NULL COMMENT 'BOOT版本',
  `cpld_version` varchar(255) DEFAULT NULL COMMENT 'CPLD版本',
  `pcb_version` varchar(255) DEFAULT NULL COMMENT 'PCB版本',
  `customized` bit(1) DEFAULT NULL COMMENT '是否定制版本',
  `release_date` date DEFAULT NULL COMMENT '版本发布日期',
  `version_desc` varchar(1000) DEFAULT NULL COMMENT '版本说明',
  `event_time` datetime(3) NOT NULL COMMENT '来源事件发生时间',
  `received_time` datetime(3) NOT NULL COMMENT '平台接收时间',
  `change_reason` varchar(500) DEFAULT NULL COMMENT '版本变更原因',
  `changed_by` varchar(128) DEFAULT NULL COMMENT '版本变更人',
  `revoked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否撤销',
  `mapping_status` varchar(32) NOT NULL COMMENT '设备映射状态',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_network_event_source` (`tenant_id`, `source_system`, `source_device_key`, `source_event_key`),
  KEY `idx_ast_device_network_event_device` (`tenant_id`, `device_sn`, `event_time`, `id`),
  KEY `idx_ast_device_network_event_mapping` (`tenant_id`, `mapping_status`, `received_time`, `id`),
  CONSTRAINT `fk_ast_device_network_event_device`
    FOREIGN KEY (`tenant_id`, `device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备在网软件版本来源事件';
