-- F-CUT-001 / CUT-07: versioned cutover configuration aggregate.
CREATE TABLE IF NOT EXISTS `cut_cutover_configuration_revision` (
  `id` bigint NOT NULL,
  `configuration_code` varchar(64) NOT NULL,
  `configuration_name` varchar(128) NOT NULL,
  `revision_no` int NOT NULL,
  `status_code` varchar(32) NOT NULL,
  `effective_from` datetime DEFAULT NULL,
  `effective_to` datetime DEFAULT NULL,
  `dictionary_snapshot` json NOT NULL,
  `dimension_definition_snapshot` json NOT NULL,
  `plan_template_section_snapshot` json NOT NULL,
  `validation_result_snapshot` json DEFAULT NULL,
  `change_summary` varchar(500) DEFAULT NULL,
  `published_by` bigint DEFAULT NULL,
  `published_at` datetime DEFAULT NULL,
  `disabled_by` bigint DEFAULT NULL,
  `disabled_at` datetime DEFAULT NULL,
  `published_marker` tinyint GENERATED ALWAYS AS (
    CASE WHEN `status_code` = 'PUBLISHED' AND `deleted` = 0 THEN 1 ELSE NULL END
  ) STORED,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_config_code_revision` (`tenant_id`, `configuration_code`, `revision_no`),
  UNIQUE KEY `uk_cut_config_current_published` (`tenant_id`, `configuration_code`, `published_marker`),
  KEY `idx_cut_config_status` (`tenant_id`, `status_code`, `update_time`, `id`),
  CONSTRAINT `chk_cut_config_status` CHECK (`status_code` IN ('DRAFT', 'PUBLISHED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CUT-07割接配置根修订';

CREATE TABLE IF NOT EXISTS `cut_cutover_checklist_item_definition_revision` (
  `id` bigint NOT NULL,
  `configuration_revision_id` bigint NOT NULL,
  `stable_item_key` varchar(96) NOT NULL,
  `item_definition_version` int NOT NULL DEFAULT 1,
  `item_type_code` varchar(32) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `item_description` text DEFAULT NULL,
  `interface_format_code` varchar(32) NOT NULL,
  `interface_schema` json NOT NULL,
  `feedback_format_code` varchar(64) NOT NULL,
  `required_flag` bit(1) NOT NULL DEFAULT b'0',
  `work_mode_code` varchar(32) NOT NULL DEFAULT 'MANUAL',
  `external_source_config` json DEFAULT NULL,
  `subtable_code` varchar(64) DEFAULT NULL,
  `status_code` varchar(16) NOT NULL DEFAULT 'ENABLED',
  `sort_order` int NOT NULL DEFAULT 0,
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_config_item_key` (`tenant_id`, `configuration_revision_id`, `stable_item_key`),
  KEY `idx_cut_config_item_type` (`tenant_id`, `configuration_revision_id`, `item_type_code`, `status_code`, `sort_order`),
  CONSTRAINT `chk_cut_config_item_type` CHECK (`item_type_code` IN ('BUSINESS_SURVEY', 'RISK', 'DUAL_MACHINE_CHECK')),
  CONSTRAINT `chk_cut_config_item_status` CHECK (`status_code` IN ('ENABLED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CUT-07统一采集项定义修订';

CREATE TABLE IF NOT EXISTS `cut_cutover_checklist_binding_rule_revision` (
  `id` bigint NOT NULL,
  `configuration_revision_id` bigint NOT NULL,
  `stable_rule_key` varchar(96) NOT NULL,
  `item_definition_id` bigint NOT NULL,
  `item_definition_version` int NOT NULL DEFAULT 1,
  `dimension_condition_snapshot` json NOT NULL,
  `priority` int NOT NULL DEFAULT 0,
  `status_code` varchar(16) NOT NULL DEFAULT 'ENABLED',
  `version` int NOT NULL DEFAULT 0,
  `creator` varchar(64) DEFAULT '',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updater` varchar(64) DEFAULT '',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `tenant_id` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_config_rule_key` (`tenant_id`, `configuration_revision_id`, `stable_rule_key`),
  KEY `idx_cut_config_rule_item` (`tenant_id`, `configuration_revision_id`, `item_definition_id`, `status_code`, `priority`),
  CONSTRAINT `chk_cut_config_rule_status` CHECK (`status_code` IN ('ENABLED', 'DISABLED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='CUT-07统一采集项绑定规则修订';
