-- F-CUT-002 割接任务接入与P2人工分级新Owner表。
-- 旧pms_cut_*表、菜单和权限保持不变；CURRENT_FORWARD数据迁移由受控PLT批次完成。

CREATE TABLE `cut_task` (
  `id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL,
  `project_id` bigint NOT NULL,
  `previous_task_id` bigint DEFAULT NULL,
  `task_no` varchar(64) NOT NULL,
  `task_name` varchar(128) NOT NULL,
  `background` varchar(4000) DEFAULT NULL,
  `cutover_type` varchar(32) DEFAULT NULL,
  `network_mode` varchar(32) DEFAULT NULL,
  `scheduled_time` datetime(3) DEFAULT NULL,
  `task_origin` varchar(32) NOT NULL,
  `intake_source_type` varchar(32) NOT NULL,
  `source_system` varchar(64) DEFAULT NULL,
  `source_business_no` varchar(128) DEFAULT NULL,
  `business_event_id` varchar(128) DEFAULT NULL,
  `current_stage` varchar(8) DEFAULT NULL,
  `task_status` varchar(32) NOT NULL,
  `owner_user_id` bigint DEFAULT NULL,
  `customer_id` bigint DEFAULT NULL,
  `implementation_readiness_snapshot_id` bigint DEFAULT NULL,
  `implementation_readiness_snapshot_version` bigint DEFAULT NULL,
  `project_scope_version` bigint DEFAULT NULL,
  `project_context_snapshot` json DEFAULT NULL,
  `device_scope_watermark` json DEFAULT NULL,
  `customer_context_snapshot` json DEFAULT NULL,
  `readiness_context_snapshot` json DEFAULT NULL,
  `manual_grade` varchar(8) DEFAULT NULL,
  `current_assessment_id` bigint DEFAULT NULL,
  `legacy_task_id` bigint DEFAULT NULL,
  `legacy_cutover_type_raw` varchar(32) DEFAULT NULL,
  `legacy_network_mode_raw` varchar(32) DEFAULT NULL,
  `legacy_status_value` tinyint DEFAULT NULL,
  `legacy_source_version` int DEFAULT NULL,
  `legacy_mapping_version` varchar(64) DEFAULT NULL,
  `version` int NOT NULL,
  `creator` varchar(64) NOT NULL,
  `create_time` datetime(3) NOT NULL,
  `updater` varchar(64) NOT NULL,
  `update_time` datetime(3) NOT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_task_project_no` (`tenant_id`,`project_id`,`task_no`),
  UNIQUE KEY `uk_cut_task_previous` (`tenant_id`,`previous_task_id`),
  UNIQUE KEY `uk_cut_task_source` (`tenant_id`,`source_system`,`source_business_no`),
  UNIQUE KEY `uk_cut_task_event` (`tenant_id`,`business_event_id`),
  UNIQUE KEY `uk_cut_task_legacy` (`tenant_id`,`legacy_task_id`),
  KEY `idx_cut_task_project_status` (`tenant_id`,`project_id`,`task_status`,`deleted`),
  CONSTRAINT `chk_cut_task_version` CHECK (`version` >= 0),
  CONSTRAINT `chk_cut_task_origin` CHECK (`task_origin` IN ('NEW_PLATFORM','LEGACY_FORWARD')),
  CONSTRAINT `chk_cut_task_source_type` CHECK (`intake_source_type` IN ('SELF_CREATED','ITR','PROJECT_EVENT','LEGACY_FORWARD')),
  CONSTRAINT `chk_cut_task_stage` CHECK (`current_stage` IS NULL OR `current_stage` IN ('P2','P3','P4')),
  CONSTRAINT `chk_cut_task_status` CHECK (`task_status` IN ('GRADE_CONFIRMING','SURVEYING','PLAN_DRAFTING','LEGACY_UNKNOWN')),
  CONSTRAINT `chk_cut_task_grade` CHECK (`manual_grade` IS NULL OR `manual_grade` IN ('A','B','C','D')),
  CONSTRAINT `chk_cut_task_previous` CHECK (`previous_task_id` IS NULL OR `previous_task_id` <> `id`),
  CONSTRAINT `chk_cut_task_source_union` CHECK (
    (`intake_source_type`='SELF_CREATED' AND `task_origin`='NEW_PLATFORM' AND `source_system` IS NULL AND `source_business_no` IS NULL AND `business_event_id` IS NULL)
    OR (`intake_source_type`='ITR' AND `task_origin`='NEW_PLATFORM' AND `source_system` IS NOT NULL AND `source_business_no` IS NOT NULL AND `business_event_id` IS NULL)
    OR (`intake_source_type`='PROJECT_EVENT' AND `task_origin`='NEW_PLATFORM' AND `source_system` IS NULL AND `source_business_no` IS NULL AND `business_event_id` IS NOT NULL)
    OR (`intake_source_type`='LEGACY_FORWARD' AND `task_origin`='LEGACY_FORWARD' AND `source_system` IS NULL AND `source_business_no` IS NULL AND `business_event_id` IS NULL)
  )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='F-CUT-002割接任务';

CREATE TABLE `cut_task_device_scope` (
  `id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL,
  `cutover_task_id` bigint NOT NULL,
  `project_id` bigint NOT NULL,
  `device_id` bigint NOT NULL,
  `serial_number_snapshot` varchar(128) NOT NULL,
  `project_assignment_version` bigint NOT NULL,
  `active_marker` tinyint DEFAULT NULL,
  `version` int NOT NULL,
  `creator` varchar(64) NOT NULL,
  `create_time` datetime(3) NOT NULL,
  `updater` varchar(64) NOT NULL,
  `update_time` datetime(3) NOT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_task_device` (`tenant_id`,`cutover_task_id`,`device_id`),
  UNIQUE KEY `uk_cut_active_device` (`tenant_id`,`project_id`,`device_id`,`active_marker`),
  KEY `idx_cut_task_device_order` (`tenant_id`,`cutover_task_id`,`device_id`),
  CONSTRAINT `chk_cut_task_device_values` CHECK (`device_id` > 0 AND `project_assignment_version` >= 0 AND `version` >= 0),
  CONSTRAINT `chk_cut_task_device_marker` CHECK (`active_marker` IS NULL OR `active_marker`=1),
  CONSTRAINT `chk_cut_task_device_serial` CHECK (CHAR_LENGTH(TRIM(`serial_number_snapshot`)) BETWEEN 1 AND 128)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='F-CUT-002任务设备活动范围';

CREATE TABLE `cut_task_stage_history` (
  `id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL,
  `cutover_task_id` bigint NOT NULL,
  `sequence_no` int NOT NULL,
  `from_stage` varchar(8) NOT NULL,
  `to_stage` varchar(8) NOT NULL,
  `from_status` varchar(32) DEFAULT NULL,
  `to_status` varchar(32) NOT NULL,
  `trigger_type` varchar(64) NOT NULL,
  `trigger_reference_id` bigint DEFAULT NULL,
  `actor_id` bigint NOT NULL,
  `correlation_id` varchar(128) NOT NULL,
  `occurred_at` datetime(3) NOT NULL,
  `creator` varchar(64) NOT NULL,
  `create_time` datetime(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_stage_sequence` (`tenant_id`,`cutover_task_id`,`sequence_no`),
  CONSTRAINT `chk_cut_stage_values` CHECK (`sequence_no` > 0 AND `actor_id` >= 0),
  CONSTRAINT `chk_cut_stage_code` CHECK (`from_stage` IN ('P1','P2','P3','P4') AND `to_stage` IN ('P2','P3','P4')),
  CONSTRAINT `chk_cut_stage_trigger` CHECK (`trigger_type` IN ('P1_ACCEPTED','P2_ASSESSMENT_SUBMITTED','P2_ASSESSMENT_INVALIDATED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='F-CUT-002任务阶段不可变历史';

CREATE TABLE `cut_assessment` (
  `id` bigint NOT NULL,
  `tenant_id` bigint NOT NULL,
  `cutover_task_id` bigint NOT NULL,
  `assessment_version` int NOT NULL,
  `assessment_status` varchar(32) NOT NULL,
  `questionnaire_template_code` varchar(64) NOT NULL,
  `questionnaire_template_version` bigint NOT NULL,
  `answer_snapshot` json NOT NULL,
  `context_snapshot` json NOT NULL,
  `manual_grade` varchar(8) DEFAULT NULL,
  `simple_flow` bit(1) NOT NULL,
  `submitted_by` bigint DEFAULT NULL,
  `submitted_at` datetime(3) DEFAULT NULL,
  `invalidated_by` bigint DEFAULT NULL,
  `invalidated_at` datetime(3) DEFAULT NULL,
  `invalidation_reason` varchar(1000) DEFAULT NULL,
  `current_marker` tinyint DEFAULT NULL,
  `version` int NOT NULL,
  `creator` varchar(64) NOT NULL,
  `create_time` datetime(3) NOT NULL,
  `updater` varchar(64) NOT NULL,
  `update_time` datetime(3) NOT NULL,
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_cut_assessment_version` (`tenant_id`,`cutover_task_id`,`assessment_version`),
  UNIQUE KEY `uk_cut_assessment_current` (`tenant_id`,`cutover_task_id`,`current_marker`),
  CONSTRAINT `chk_cut_assessment_values` CHECK (`assessment_version` > 0 AND `questionnaire_template_version` > 0 AND `version` >= 0),
  CONSTRAINT `chk_cut_assessment_status` CHECK (`assessment_status` IN ('DRAFT','SUBMITTED','INVALIDATED')),
  CONSTRAINT `chk_cut_assessment_grade` CHECK (`manual_grade` IS NULL OR `manual_grade` IN ('A','B','C','D')),
  CONSTRAINT `chk_cut_assessment_marker` CHECK (`current_marker` IS NULL OR `current_marker`=1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='F-CUT-002人工分级评估';

INSERT INTO `system_menu`
(`id`, `name`, `permission`, `type`, `sort`, `parent_id`, `path`, `icon`, `component`, `component_name`,
 `status`, `visible`, `keep_alive`, `always_show`, `creator`, `create_time`, `updater`, `update_time`, `deleted`)
VALUES
(992602050001, '割接任务工作台', 'pms:cutover-task:query', 2, 6, 19263,
 'cutover-task', 'ep:switch', 'pms/cutover/cutover-task/index', 'PmsCutoverTask',
 0, b'1', b'1', b'1', 'seed', NOW(), 'seed', NOW(), b'0'),
(992602050002, '割接任务查询', 'pms:cutover-task:query', 3, 10, 992602050001,
 '', '', NULL, NULL, 0, b'1', b'1', b'1', 'seed', NOW(), 'seed', NOW(), b'0'),
(992602050003, '创建割接任务', 'pms:cutover-task:create', 3, 20, 992602050001,
 '', '', NULL, NULL, 0, b'1', b'1', b'1', 'seed', NOW(), 'seed', NOW(), b'0'),
(992602050004, '保存人工评估', 'pms:cutover-task:save-assessment', 3, 30, 992602050001,
 '', '', NULL, NULL, 0, b'1', b'1', b'1', 'seed', NOW(), 'seed', NOW(), b'0'),
(992602050005, '提交人工评估', 'pms:cutover-task:submit-assessment', 3, 40, 992602050001,
 '', '', NULL, NULL, 0, b'1', b'1', b'1', 'seed', NOW(), 'seed', NOW(), b'0')
ON DUPLICATE KEY UPDATE
 `name`=VALUES(`name`), `permission`=VALUES(`permission`), `type`=VALUES(`type`),
 `sort`=VALUES(`sort`), `parent_id`=VALUES(`parent_id`), `path`=VALUES(`path`),
 `icon`=VALUES(`icon`), `component`=VALUES(`component`), `component_name`=VALUES(`component_name`),
 `status`=0, `visible`=b'1', `keep_alive`=VALUES(`keep_alive`),
 `always_show`=VALUES(`always_show`), `updater`='seed', `update_time`=NOW(), `deleted`=b'0';
