-- Chronologically replayed from 8425805911703c3c75387ba7e9bea75dedd6f076 (prereq-parallel-check-kKiAdn), original sql/migrations/V104__device_ops_integration_foundation.sql.
-- Renumbered after current master; Feature status is not promoted by this receipt.

CREATE TABLE IF NOT EXISTS infra_file_artifact (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    source_system VARCHAR(64) NOT NULL,
    source_artifact_key VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    access_scope VARCHAR(32) NOT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_infra_artifact_source (tenant_id, source_system, source_artifact_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS infra_file_version (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    artifact_id BIGINT NOT NULL,
    config_id BIGINT NOT NULL,
    content_sha256 CHAR(64) NOT NULL,
    size BIGINT NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    scan_status VARCHAR(32) NOT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_infra_version_digest (tenant_id, artifact_id, content_sha256),
    KEY idx_infra_version_artifact (artifact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plt_device_credential (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    credential_code VARCHAR(64) NOT NULL,
    credential_type VARCHAR(32) NOT NULL,
    username VARCHAR(128) NOT NULL,
    encrypted_secret TEXT NULL,
    kms_reference VARCHAR(512) NULL,
    credential_version BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plt_credential_code (tenant_id, credential_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plt_credential_grant (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    credential_id BIGINT NOT NULL,
    grantee_type VARCHAR(32) NOT NULL,
    grantee_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NULL,
    device_id VARCHAR(64) NULL,
    protocol VARCHAR(16) NULL,
    expires_at DATETIME NULL,
    status VARCHAR(32) NOT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_plt_grant_credential (credential_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plt_collection_batch (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    batch_no VARCHAR(64) NOT NULL,
    source_context VARCHAR(32) NOT NULL,
    source_object_type VARCHAR(64) NOT NULL,
    source_object_id VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    task_count INT NOT NULL,
    success_count INT NOT NULL DEFAULT 0,
    failure_count INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plt_batch_idempotency (tenant_id, idempotency_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plt_collection_task (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    batch_id BIGINT NOT NULL,
    platform_task_id VARCHAR(64) NOT NULL,
    source_context VARCHAR(32) NOT NULL,
    source_object_type VARCHAR(64) NOT NULL,
    source_object_id VARCHAR(64) NOT NULL,
    project_id VARCHAR(64) NULL,
    device_id VARCHAR(64) NOT NULL,
    device_name VARCHAR(128) NOT NULL,
    host VARCHAR(255) NOT NULL,
    port INT NOT NULL,
    protocol VARCHAR(16) NOT NULL,
    template_id VARCHAR(64) NOT NULL,
    template_version VARCHAR(64) NOT NULL,
    template_hash CHAR(64) NOT NULL,
    credential_mode VARCHAR(32) NOT NULL,
    credential_id BIGINT NULL,
    grant_snapshot_id BIGINT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    completion_mode VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    technical_stage VARCHAR(32) NOT NULL,
    external_task_id VARCHAR(128) NULL,
    external_status VARCHAR(64) NULL,
    result_version BIGINT NULL,
    file_version_id BIGINT NULL,
    quarantine_evidence_id VARCHAR(128) NULL,
    failure_category VARCHAR(64) NULL,
    consumer_context VARCHAR(32) NULL,
    consumer_object_type VARCHAR(64) NULL,
    consumer_object_id VARCHAR(64) NULL,
    consumed_result_version BIGINT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plt_collection_task_id (tenant_id, platform_task_id),
    UNIQUE KEY uk_plt_collection_idempotency (tenant_id, idempotency_key),
    KEY idx_plt_collection_batch (batch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS plt_collection_callback_record (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    platform_task_id VARCHAR(64) NOT NULL,
    callback_id VARCHAR(128) NOT NULL,
    receipt_id BIGINT NOT NULL,
    sequence_no BIGINT NOT NULL,
    external_task_id VARCHAR(128) NOT NULL,
    external_status VARCHAR(64) NOT NULL,
    mapped_status VARCHAR(32) NOT NULL,
    result_version BIGINT NOT NULL,
    file_version_id BIGINT NULL,
    quarantine_evidence_id VARCHAR(128) NULL,
    failure_category VARCHAR(64) NULL,
    processing_result VARCHAR(32) NOT NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_plt_callback (tenant_id, platform_task_id, callback_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS int_device_ops_dispatch_attempt (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    platform_task_id VARCHAR(64) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    attempt_no INT NOT NULL,
    request_digest CHAR(64) NOT NULL,
    endpoint VARCHAR(512) NOT NULL,
    duration_ms BIGINT NULL,
    http_status INT NULL,
    external_error VARCHAR(512) NULL,
    external_task_id VARCHAR(128) NULL,
    retry_reason VARCHAR(256) NULL,
    trace_id VARCHAR(128) NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_int_dispatch_attempt (tenant_id, platform_task_id, operation_type, attempt_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS int_device_ops_callback_receipt (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    callback_id VARCHAR(128) NOT NULL,
    manifest_digest CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    retryable BIT NOT NULL DEFAULT 0,
    file_version_id BIGINT NULL,
    quarantine_evidence_id VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    platform_task_id VARCHAR(64) NOT NULL,
    platform_submission_status VARCHAR(32) NULL,
    trace_id VARCHAR(128) NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_int_callback_receipt (tenant_id, provider_code, callback_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS int_device_ops_reconcile_batch (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    batch_no VARCHAR(64) NOT NULL,
    provider_code VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    scanned_count INT NOT NULL DEFAULT 0,
    repaired_count INT NOT NULL DEFAULT 0,
    conflict_count INT NOT NULL DEFAULT 0,
    started_at DATETIME NOT NULL,
    completed_at DATETIME NULL,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_int_reconcile_batch (tenant_id, batch_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
