-- Version-owned design/rules and per-node execution evidence. No historical backfill or data deletion.
CREATE TABLE proj_project_plan_version (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    revision_no INT NOT NULL,
    status VARCHAR(16) NOT NULL,
    source_template_revision_id BIGINT NULL,
    base_plan_version_id BIGINT NULL,
    designer_document JSON NOT NULL,
    execution_snapshot JSON NULL,
    effective_at DATETIME(3) NULL,
    closed_at DATETIME(3) NULL,
    closure_result JSON NULL,
    version INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_plan_revision (tenant_id, project_id, revision_no),
    CONSTRAINT ck_project_plan_status CHECK (status IN ('DRAFT','EFFECTIVE','SUPERSEDED')),
    CONSTRAINT ck_project_plan_payload CHECK (status='DRAFT' OR (execution_snapshot IS NOT NULL AND effective_at IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE proj_project ADD COLUMN active_plan_version_id BIGINT NULL,
    ADD KEY idx_project_active_plan (tenant_id, active_plan_version_id);

CREATE TABLE proj_project_node_execution (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    plan_version_id BIGINT NOT NULL,
    node_key VARCHAR(128) NOT NULL,
    node_kind VARCHAR(16) NOT NULL,
    node_instance_id BIGINT NOT NULL,
    contract_id BIGINT NOT NULL,
    round_no INT NOT NULL,
    current_marker TINYINT NULL,
    status VARCHAR(16) NOT NULL,
    admitted_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    started_plan_version_id BIGINT NULL,
    submitted_at DATETIME(3) NULL,
    submitted_by BIGINT NULL,
    submission_note VARCHAR(2000) NULL,
    ended_at DATETIME(3) NULL,
    result_snapshot JSON NULL,
    version INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_node_execution_round (tenant_id, project_id, node_key, round_no),
    UNIQUE KEY uk_node_current_execution (tenant_id, project_id, node_key, current_marker),
    KEY idx_node_execution_plan (tenant_id, project_id, plan_version_id),
    CONSTRAINT ck_node_execution_kind CHECK (node_kind IN ('STAGE','TASK')),
    CONSTRAINT ck_node_execution_status CHECK (status IN ('PENDING','ACTIVE','DONE','TERMINATED')),
    CONSTRAINT ck_node_execution_round CHECK (round_no > 0 AND (current_marker IS NULL OR current_marker=1)),
    CONSTRAINT ck_node_execution_submission CHECK (submitted_at IS NULL OR (submitted_by IS NOT NULL AND started_at IS NOT NULL)),
    CONSTRAINT ck_node_execution_end CHECK (status NOT IN ('DONE','TERMINATED') OR (ended_at IS NOT NULL AND result_snapshot IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
