-- New ordinary survey entity; the legacy table is the migration source.
CREATE TABLE sol_site_survey (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    survey_date DATE NULL,
    surveyor_user_id BIGINT NULL,
    location VARCHAR(255) NULL,
    address_id BIGINT NULL,
    address_version INT UNSIGNED NULL,
    site_id BIGINT NULL,
    site_version INT UNSIGNED NULL,
    site_location_id BIGINT NULL,
    site_location_version INT UNSIGNED NULL,
    location_resolution_status VARCHAR(16) NOT NULL DEFAULT 'UNRESOLVED',
    address_snapshot TEXT NULL,
    location_snapshot TEXT NULL,
    power_supply VARCHAR(500) NULL,
    cabinet VARCHAR(500) NULL,
    network_port VARCHAR(500) NULL,
    fiber VARCHAR(500) NULL,
    module VARCHAR(500) NULL,
    cable VARCHAR(500) NULL,
    ground VARCHAR(500) NULL,
    construction_resource VARCHAR(500) NULL,
    conclusion MEDIUMTEXT NULL,
    remark VARCHAR(500) NULL,
    cabinet_ready BIT(1) NULL,
    cable_ready BIT(1) NULL,
    module_ready BIT(1) NULL,
    original_module BIT(1) NULL,
    manufacturer_installation BIT(1) NULL,
    rail_tray_required BIT(1) NULL,
    material_matches BIT(1) NULL,
    required_end_date DATE NULL,
    status TINYINT NOT NULL DEFAULT 0,
    confirmed_at DATETIME(3) NULL,
    archived_at DATETIME(3) NULL,
    outsource_required BIT(1) NOT NULL DEFAULT b'0',
    outsource_request_id BIGINT NULL,
    version INT NOT NULL DEFAULT 0,
    creator VARCHAR(64) DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    UNIQUE KEY uk_sol_survey_code (tenant_id, project_id, code),
    CONSTRAINT chk_sol_survey_status CHECK (status IN (0, 1, 2, 3)),
    CONSTRAINT chk_sol_survey_location CHECK (location_resolution_status IN ('UNRESOLVED', 'RESOLVED'))
);

CREATE TABLE sol_site_survey_condition (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    survey_id BIGINT NOT NULL,
    condition_type VARCHAR(64) NOT NULL,
    condition_code VARCHAR(64) NOT NULL,
    sort_order INT NOT NULL,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    UNIQUE KEY uk_survey_condition_order (tenant_id, survey_id, condition_type, sort_order)
);

CREATE TABLE sol_site_survey_material (
    id BIGINT NOT NULL PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    survey_id BIGINT NOT NULL,
    device_id BIGINT NULL,
    project_id BIGINT NOT NULL,
    sn VARCHAR(255) NOT NULL,
    product_code VARCHAR(255) NULL,
    product_name VARCHAR(500) NULL,
    product_model VARCHAR(500) NULL,
    reason TEXT NULL,
    sort_order INT NOT NULL,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    UNIQUE KEY uk_survey_material (tenant_id, survey_id, sn)
);

