CREATE TABLE com_crm_execution_order (
    id BIGINT NOT NULL COMMENT '主键ID', tenant_id BIGINT NOT NULL COMMENT '租户ID',
    source_system VARCHAR(32) NOT NULL DEFAULT 'CRM' COMMENT '来源系统', execution_no VARCHAR(255) NOT NULL COMMENT '执行单编号',
    project_code VARCHAR(255) NULL COMMENT '项目编码', project_name VARCHAR(1024) NULL COMMENT '项目名称', primary_project_id BIGINT NULL COMMENT '主项目ID',
    sales_rep_code VARCHAR(64) NULL COMMENT '销售代表编码', sales_rep_name VARCHAR(128) NULL COMMENT '销售代表名称', sales_rep_phone VARCHAR(300) NULL COMMENT '销售代表电话',
    market_code VARCHAR(64) NULL COMMENT '市场部编码', market_name VARCHAR(255) NULL COMMENT '市场部名称',
    system_source_key VARCHAR(64) NULL COMMENT '系统部来源键', system_code VARCHAR(64) NULL COMMENT '系统部编码', system_name VARCHAR(255) NULL COMMENT '系统部名称',
    expend_source_key VARCHAR(64) NULL COMMENT '拓展部来源键', expend_code VARCHAR(64) NULL COMMENT '拓展部编码', expend_name VARCHAR(255) NULL COMMENT '拓展部名称',
    industry_code VARCHAR(64) NULL COMMENT '行业编码', industry_name VARCHAR(255) NULL COMMENT '行业名称',
    department_id BIGINT NULL COMMENT '办事处ID', department_code VARCHAR(64) NULL COMMENT '办事处编码', department_name VARCHAR(128) NULL COMMENT '办事处名称',
    service_type_name VARCHAR(128) NULL COMMENT '服务类型名称', channel_name VARCHAR(1024) NULL COMMENT '渠道名称',
    engineering_fee_raw VARCHAR(64) NULL COMMENT '工程费用原始', engineering_fee DECIMAL(20,4) NULL COMMENT '工程费用',
    source_object_id VARCHAR(64) NULL COMMENT '来源对象ID', apply_type VARCHAR(64) NULL COMMENT '申请类型编码',
    company_id BIGINT NULL COMMENT '公司ID', company_code VARCHAR(64) NULL COMMENT '公司编码', company_name VARCHAR(255) NULL COMMENT '公司名称',
    customer_project_name VARCHAR(1024) NULL COMMENT '客户项目名称', final_customer_name VARCHAR(1024) NULL COMMENT '最终客户名称', agent_name VARCHAR(1024) NULL COMMENT '代理商名称',
    project_manager_code VARCHAR(1024) NULL COMMENT '项目负责人编码', project_manager_name VARCHAR(512) NULL COMMENT '项目负责人名称', decision_path VARCHAR(1024) NULL COMMENT '决策路径',
    required_in_date DATE NULL COMMENT '要求入场日期', receiver_name VARCHAR(512) NULL COMMENT '收件人名称', receiver_contact VARCHAR(300) NULL COMMENT '收件人联系人',
    receiver_address VARCHAR(1024) NULL COMMENT '收件人地址', loan_reason TEXT NULL COMMENT '借用原因', project_type VARCHAR(32) NULL COMMENT '项目类型编码',
    major_project_level VARCHAR(255) NULL COMMENT '重大项目级别', project_amount DECIMAL(20,4) NULL COMMENT '项目金额', af_project_amount DECIMAL(20,4) NULL COMMENT '安服项目金额',
    submit_time DATETIME(3) NULL COMMENT '提交时间', predicted_bid_time DATETIME(3) NULL COMMENT '预计中标时间', contact_name VARCHAR(255) NULL COMMENT '联系人名称', contact_phone VARCHAR(128) NULL COMMENT '联系人电话',
    af_evidence_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN' COMMENT '安服证据状态：CONFIRMED已确认，UNKNOWN未知', source_sync_time DATETIME(3) NULL COMMENT '来源同步时间',
    status VARCHAR(32) NOT NULL COMMENT '状态', version INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    creator VARCHAR(64) NOT NULL DEFAULT '' COMMENT '创建人', create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    updater VARCHAR(64) NOT NULL DEFAULT '' COMMENT '更新人', update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '更新时间', deleted TINYINT NOT NULL DEFAULT 0 COMMENT '删除标志：0否，1是',
    PRIMARY KEY (id), UNIQUE KEY uk_crm_execution_order_tenant_row (tenant_id,id),
    UNIQUE KEY uk_crm_execution (tenant_id,source_system,execution_no),
    KEY idx_crm_execution_project (tenant_id,primary_project_id,status), KEY idx_crm_execution_source_project (tenant_id,project_code,execution_no),
    KEY idx_crm_execution_company_office (tenant_id,company_id,department_id,status,id), KEY idx_crm_execution_company_office_code (tenant_id,company_code,department_code,status,id),
    CONSTRAINT chk_crm_execution_deleted CHECK (deleted IN (0,1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='CRM执行单辅助主档，安服仅保存正向证据';
