-- Existing customer solution UploadFile accepts doc/xls/ppt/txt/pdf (including OOXML extensions). Preserve those actual formats.
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','doc'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('doc'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','docx'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('docx'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','xls'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('xls'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','xlsx'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('xlsx'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','ppt'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('ppt'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','pptx'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('pptx'));
UPDATE plt_delivery_type SET allowed_media_json=JSON_ARRAY_APPEND(allowed_media_json,'$','txt'),updater='customer-solution-delivery',update_time=NOW(3) WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0' AND JSON_VALID(allowed_media_json) AND NOT JSON_CONTAINS(allowed_media_json,JSON_QUOTE('txt'));
-- Existing native result type from RequirementAnalysisBusinessResultSource; no new business state or Gate.
INSERT INTO plt_delivery_type(type_code,name,category,allowed_media_json,max_size_bytes,enabled,remark,version,tenant_id,creator,create_time,deleted)
SELECT 'REQUIREMENT_ANALYSIS_COMPLETED','需求分析完成修订','业务成果','[]',1,b'1','Existing effective completed native revision result',0,t.tenant_id,'native-ra-result',NOW(3),b'0'
FROM(SELECT DISTINCT tenant_id FROM plt_delivery_type WHERE type_code='IMPLEMENTATION_PLAN' AND deleted=b'0')t
WHERE NOT EXISTS(SELECT 1 FROM plt_delivery_type d WHERE d.tenant_id=t.tenant_id AND d.type_code='REQUIREMENT_ANALYSIS_COMPLETED' AND d.deleted=b'0');
