CREATE TABLE `ast_address` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `tenant_id` bigint NOT NULL,
    `country_code` varchar(32) NULL,
    `country_name` varchar(128) NULL,
    `province_code` varchar(32) NULL,
    `province_name` varchar(128) NULL,
    `city_code` varchar(32) NULL,
    `city_name` varchar(128) NULL,
    `district_code` varchar(32) NULL,
    `district_name` varchar(128) NULL,
    `detail_address` varchar(512) NOT NULL,
    `full_address` varchar(1024) NOT NULL,
    `longitude` decimal(10, 7) NULL,
    `latitude` decimal(10, 7) NULL,
    `normalized_address` varchar(1024) NULL,
    `address_fingerprint` char(64) NULL,
    `status` tinyint NOT NULL,
    `version` int unsigned NOT NULL DEFAULT 0,
    `creator` varchar(64) NULL DEFAULT '',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updater` varchar(64) NULL DEFAULT '',
    `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    KEY `idx_ast_address_fingerprint` (`tenant_id`, `address_fingerprint`),
    KEY `idx_ast_address_district` (`tenant_id`, `district_code`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产地址主数据';

CREATE TABLE `ast_site` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `tenant_id` bigint NOT NULL,
    `code` varchar(64) NOT NULL,
    `name` varchar(128) NOT NULL,
    `customer_id` bigint NULL,
    `address_id` bigint NOT NULL,
    `site_type` varchar(32) NOT NULL,
    `status` tinyint NOT NULL,
    `version` int unsigned NOT NULL DEFAULT 0,
    `creator` varchar(64) NULL DEFAULT '',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updater` varchar(64) NULL DEFAULT '',
    `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ast_site_code` (`tenant_id`, `code`, `deleted`),
    KEY `idx_ast_site_address` (`tenant_id`, `address_id`, `status`),
    KEY `idx_ast_site_customer` (`tenant_id`, `customer_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产业务站点';

CREATE TABLE `ast_site_location` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `tenant_id` bigint NOT NULL,
    `site_id` bigint NOT NULL,
    `parent_id` bigint NULL,
    `code` varchar(64) NOT NULL,
    `name` varchar(128) NOT NULL,
    `location_type` varchar(32) NOT NULL,
    `tree_path` varchar(2048) NOT NULL,
    `tree_depth` int unsigned NOT NULL DEFAULT 0,
    `tree_sort` int NOT NULL DEFAULT 0,
    `status` tinyint NOT NULL,
    `version` int unsigned NOT NULL DEFAULT 0,
    `creator` varchar(64) NULL DEFAULT '',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updater` varchar(64) NULL DEFAULT '',
    `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ast_site_location_code` (`tenant_id`, `site_id`, `code`, `deleted`),
    KEY `idx_ast_site_location_parent` (`tenant_id`, `site_id`, `parent_id`, `tree_sort`),
    KEY `idx_ast_site_location_path` (`tenant_id`, `site_id`, `tree_path`(255))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='站点内部任意深度位置树';

CREATE TABLE `ast_location_source_mapping` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `tenant_id` bigint NOT NULL,
    `source_system` varchar(64) NOT NULL,
    `object_type` varchar(64) NOT NULL,
    `source_key` varchar(128) NOT NULL,
    `source_version` varchar(64) NULL,
    `address_id` bigint NULL,
    `site_id` bigint NULL,
    `sync_watermark` varchar(128) NULL,
    `match_status` varchar(16) NOT NULL,
    `location_resolution_status` varchar(16) NOT NULL DEFAULT 'UNRESOLVED',
    `last_synced_at` datetime(3) NULL,
    `version` int unsigned NOT NULL DEFAULT 0,
    `creator` varchar(64) NULL DEFAULT '',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updater` varchar(64) NULL DEFAULT '',
    `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ast_location_source_key` (`tenant_id`, `source_system`, `object_type`, `source_key`, `deleted`),
    CONSTRAINT `chk_ast_location_match_status` CHECK (`match_status` IN ('PENDING', 'MATCHED', 'CONFLICT', 'INVALID')),
    CONSTRAINT `chk_ast_location_resolution_status` CHECK (`location_resolution_status` IN ('UNRESOLVED', 'RESOLVED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='地点外部来源映射';

CREATE TABLE `ast_area_department_mapping` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `tenant_id` bigint NOT NULL,
    `area_code` varchar(32) NOT NULL,
    `area_level` varchar(16) NOT NULL,
    `mapping_type` varchar(32) NOT NULL,
    `department_code` varchar(64) NOT NULL,
    `effective_from` datetime(3) NOT NULL,
    `effective_to` datetime(3) NULL,
    `status` tinyint NOT NULL,
    `version` int unsigned NOT NULL DEFAULT 0,
    `creator` varchar(64) NULL DEFAULT '',
    `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updater` varchar(64) NULL DEFAULT '',
    `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_ast_area_department_effective`
        (`tenant_id`, `area_code`, `area_level`, `mapping_type`, `effective_from`),
    KEY `idx_ast_area_department_current`
        (`tenant_id`, `area_code`, `area_level`, `mapping_type`, `status`, `effective_to`),
    CONSTRAINT `chk_ast_area_level` CHECK (`area_level` IN ('COUNTRY', 'PROVINCE', 'CITY', 'DISTRICT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='行政区划与部门时态映射';
