CREATE TABLE `com_order_line` (
    `id` bigint NOT NULL,
    `source_system` varchar(32) NOT NULL,
    `source_key` varchar(128) NOT NULL,
    `source_version` varchar(64) NOT NULL,
    `order_id` bigint NOT NULL,
    `line_code` varchar(64) NOT NULL,
    `item_code` varchar(128) DEFAULT NULL,
    `quantity` decimal(18, 6) DEFAULT NULL,
    `unit_code` varchar(32) DEFAULT NULL,
    `quantity_status` varchar(32) NOT NULL,
    `source_updated_at` datetime DEFAULT NULL,
    `synced_at` datetime NOT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_com_order_line_source` (`tenant_id`, `source_system`, `source_key`),
    KEY `idx_com_order_line_order` (`tenant_id`, `order_id`, `line_code`),
    CONSTRAINT `ck_com_order_line_quantity_status` CHECK (`quantity_status` IN ('CONFIRMED', 'PENDING_AUTHORITY')),
    CONSTRAINT `ck_com_order_line_quantity` CHECK (`quantity` IS NULL OR `quantity` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商务订单行权威数量切片';

CREATE TABLE `com_delivery_scope` (
    `id` bigint NOT NULL,
    `order_line_id` bigint NOT NULL,
    `project_id` bigint NOT NULL,
    `allocated_qty` decimal(18, 6) NOT NULL,
    `scope_status` varchar(32) NOT NULL,
    `allocation_version` bigint NOT NULL,
    `source_evidence` varchar(255) DEFAULT NULL,
    `effective_from` datetime NOT NULL,
    `effective_to` datetime DEFAULT NULL,
    `current_marker` tinyint GENERATED ALWAYS AS (
        CASE WHEN `scope_status` = 'ACTIVE' AND `effective_to` IS NULL THEN 1 ELSE NULL END
    ) STORED,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_com_scope_version` (`tenant_id`, `order_line_id`, `project_id`, `allocation_version`),
    UNIQUE KEY `uk_com_scope_current` (`tenant_id`, `order_line_id`, `project_id`, `current_marker`),
    KEY `idx_com_scope_current` (`tenant_id`, `order_line_id`, `scope_status`, `effective_to`),
    KEY `idx_com_scope_project` (`tenant_id`, `project_id`, `scope_status`, `effective_to`),
    CONSTRAINT `ck_com_scope_quantity` CHECK (`allocated_qty` > 0),
    CONSTRAINT `ck_com_scope_status` CHECK (`scope_status` IN ('ACTIVE', 'RELEASED', 'CONFLICT')),
    CONSTRAINT `ck_com_scope_effective_range` CHECK (`effective_to` IS NULL OR `effective_to` >= `effective_from`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单行到项目的交付范围';

CREATE TABLE `com_delivery_scope_detail` (
    `id` bigint NOT NULL,
    `delivery_scope_id` bigint NOT NULL,
    `office_department_code` varchar(64) DEFAULT NULL,
    `serial_no` varchar(128) DEFAULT NULL,
    `allocated_qty` decimal(18, 6) NOT NULL,
    `detail_status` varchar(32) NOT NULL,
    `source_snapshot` json DEFAULT NULL,
    `version` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_com_scope_detail_dimension` (`tenant_id`, `delivery_scope_id`, `office_department_code`, `serial_no`),
    KEY `idx_com_scope_detail_scope` (`tenant_id`, `delivery_scope_id`, `detail_status`),
    CONSTRAINT `ck_com_scope_detail_quantity` CHECK (`allocated_qty` > 0),
    CONSTRAINT `ck_com_scope_detail_status` CHECK (`detail_status` IN ('ACTIVE', 'RELEASED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交付范围组合维度明细';

CREATE TABLE `com_outbox_event` (
    `id` bigint NOT NULL,
    `event_id` varchar(64) NOT NULL,
    `event_type` varchar(64) NOT NULL,
    `aggregate_type` varchar(64) NOT NULL,
    `aggregate_key` varchar(128) NOT NULL,
    `scope_version` bigint NOT NULL,
    `payload` json NOT NULL,
    `status` varchar(32) NOT NULL,
    `occurred_at` datetime NOT NULL,
    `retry_count` int NOT NULL DEFAULT 0,
    `creator` varchar(64) DEFAULT '',
    `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updater` varchar(64) DEFAULT '',
    `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `deleted` bit(1) NOT NULL DEFAULT b'0',
    `tenant_id` bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_com_outbox_event` (`tenant_id`, `event_id`),
    KEY `idx_com_outbox_dispatch` (`tenant_id`, `status`, `occurred_at`, `id`),
    CONSTRAINT `ck_com_outbox_status` CHECK (`status` IN ('PENDING', 'PUBLISHED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='商务域事务Outbox';
