CREATE TABLE `ast_device` (
  `id` bigint NOT NULL COMMENT '设备编号',
  `sn` varchar(100) NOT NULL COMMENT '租户内唯一设备序列号',
  `name` varchar(128) DEFAULT NULL COMMENT '设备名称',
  `product_code` varchar(64) DEFAULT NULL COMMENT '产品编码',
  `product_model` varchar(128) DEFAULT NULL COMMENT '产品型号',
  `product_name` varchar(128) DEFAULT NULL COMMENT '产品名称',
  `product_desc` text DEFAULT NULL COMMENT '产品描述',
  `shipment_time` datetime(3) DEFAULT NULL COMMENT '最新有效发货时间',
  `package_no` varchar(64) DEFAULT NULL COMMENT '最新有效装箱单编号',
  `contract_no` varchar(64) DEFAULT NULL COMMENT '最新有效发货合同编号',
  `shipment_record_id` bigint DEFAULT NULL COMMENT '最新有效发货记录编号',
  `project_id` bigint DEFAULT NULL COMMENT '当前直接归属项目编号',
  `project_assignment_version` int unsigned NOT NULL DEFAULT 0 COMMENT '项目归属版本',
  `customer_id` bigint DEFAULT NULL COMMENT '当前直接归属客户编号',
  `customer_assignment_version` int unsigned NOT NULL DEFAULT 0 COMMENT '客户归属版本',
  `site_id` bigint DEFAULT NULL COMMENT '当前站点编号',
  `site_location_id` bigint DEFAULT NULL COMMENT '当前站点位置编号',
  `location_resolution_status` varchar(16) NOT NULL DEFAULT 'UNRESOLVED' COMMENT '当前位置解析状态',
  `location_snapshot` text DEFAULT NULL COMMENT '当前位置快照',
  `location_effective_from` datetime(3) DEFAULT NULL COMMENT '当前位置生效时间',
  `location_record_id` bigint DEFAULT NULL COMMENT '当前位置记录编号',
  `warranty_start_date` date DEFAULT NULL COMMENT '当前维保开始日期',
  `warranty_end_date` date DEFAULT NULL COMMENT '当前维保结束日期',
  `warranty_status` varchar(32) DEFAULT NULL COMMENT '当前客观维保状态',
  `conp_version` varchar(255) DEFAULT NULL COMMENT '当前在网CONP原始版本',
  `conp_type` varchar(100) DEFAULT NULL COMMENT '当前在网CONP类型',
  `conp_series` varchar(100) DEFAULT NULL COMMENT '当前在网CONP系列',
  `conp_mark` varchar(255) DEFAULT NULL COMMENT '当前在网CONP版本掩码',
  `status` varchar(32) NOT NULL COMMENT '设备状态',
  `remark` varchar(500) DEFAULT NULL COMMENT '平台备注',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) DEFAULT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL DEFAULT 'NOT_APPLICABLE' COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_tenant_sn` (`tenant_id`, `sn`),
  KEY `idx_ast_device_project` (`tenant_id`, `project_id`, `deleted`, `id`),
  KEY `idx_ast_device_customer` (`tenant_id`, `customer_id`, `deleted`, `id`),
  KEY `idx_ast_device_product` (`tenant_id`, `product_code`, `product_model`, `deleted`, `id`),
  KEY `idx_ast_device_warranty` (`tenant_id`, `warranty_status`, `warranty_end_date`, `deleted`, `id`),
  KEY `idx_ast_device_shipment` (`tenant_id`, `shipment_time`, `deleted`, `id`),
  KEY `idx_ast_device_conp_parse` (`tenant_id`, `conp_type`, `conp_series`, `conp_mark`, `deleted`, `id`),
  CONSTRAINT `chk_ast_device_location_resolution`
    CHECK (`location_resolution_status` IN ('UNRESOLVED', 'RESOLVED')),
  CONSTRAINT `chk_ast_device_warranty_dates`
    CHECK (`warranty_end_date` IS NULL OR `warranty_start_date` IS NULL OR `warranty_end_date` >= `warranty_start_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备主档及高频当前事实投影';

CREATE TABLE `ast_device_factory_info` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '出厂信息编号',
  `device_sn` varchar(100) NOT NULL COMMENT '设备序列号',
  `manufacturer` varchar(128) DEFAULT NULL COMMENT '设备厂商',
  `manufacture_date` date DEFAULT NULL COMMENT '出厂日期',
  `factory_config` text DEFAULT NULL COMMENT '出厂配置',
  `source_system` varchar(32) NOT NULL COMMENT '来源系统',
  `source_key` varchar(128) NOT NULL COMMENT '来源键',
  `source_version` varchar(64) DEFAULT NULL COMMENT '来源版本',
  `source_updated_at` datetime(3) DEFAULT NULL COMMENT '来源更新时间',
  `synced_at` datetime(3) DEFAULT NULL COMMENT '最近成功同步时间',
  `sync_status` varchar(32) NOT NULL COMMENT '同步状态',
  `version` int unsigned NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人',
  `create_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人',
  `update_time` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT 0 COMMENT '租户编号',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ast_device_factory_info_device` (`tenant_id`, `device_sn`),
  UNIQUE KEY `uk_ast_device_factory_info_source` (`tenant_id`, `source_system`, `source_key`),
  CONSTRAINT `fk_ast_device_factory_info_device`
    FOREIGN KEY (`tenant_id`, `device_sn`) REFERENCES `ast_device` (`tenant_id`, `sn`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AST设备出厂信息';
