import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { formatLocalTime, statusLabel, statusTone } from './presentation'

const source = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')
describe('统一界面呈现契约', () => {
  it('全局配置中文 Element Plus', () => {
    const app = source('../App.vue')
    expect(app).toContain('element-plus/es/locale/lang/zh-cn')
    expect(app).toContain(':locale="zhCn"')
  })
  it('面板眉题可选且仅在提供时呈现', () => {
    const header = source('../components/PanelHeader.vue')
    expect(header).toContain('eyebrow?: string')
    expect(header).toContain('v-if="eyebrow"')
  })
  it('凭据警告仅由协议表单呈现，工作台说明使用简短中文', () => {
    const target = source('../components/TargetSelector.vue')
    const protocol = source('../components/ProtocolConnectionForm.vue')
    const project = source('../views/ProjectCollectionView.vue')
    expect(target).not.toContain('本次凭据仅保留在当前页面内存')
    expect(protocol).toContain('凭据加密存储，不回显')
    expect(project).toContain('subtitle="连接设备、执行采集并查看输出。"')
    expect(project).toContain('type="info">项目</el-text>')
    expect(project).toContain('title="可选：到期通知" name="schedule"')
    expect(project).toContain('label="SCHEDULE_DUE 回调地址"')
  })
  it('工作台辅助文案压缩为短句，安全警示缩短后仍渲染', () => {
    const target = source('../components/TargetSelector.vue')
    const protocol = source('../components/ProtocolConnectionForm.vue')
    expect(target).toContain('关闭后不关联项目/设备')
    expect(target).not.toContain('不创建虚构项目或设备')
    expect(protocol).toContain('Telnet 明文传输，仅限受控网络')
    expect(protocol).toContain('暂无保存的连接')
    expect(protocol).toContain("'凭据已保存'")
    expect(protocol).toContain("'状态异常，请重新保存'")
    expect(protocol).toContain('有未验证修改，请先验证保存')
    expect(protocol).toContain('留空不校验设备身份')
    expect(protocol).toContain('role="note"')
    expect(protocol).not.toContain('临时凭据仅保留在本页')
    expect(protocol).not.toContain('填写下方信息并验证保存即可创建')
    expect(protocol).not.toContain('可用于验证和采集，明文不会返回')
    expect(protocol).not.toContain('提交采集前必须验证并保存，或切换为临时连接')
    expect(protocol).not.toContain('可能受到中间人攻击')
    expect(protocol).not.toContain('自动模式适用于常见交互式终端')
  })
  it('采集面板与解析侧栏辅助文案压缩为短句', () => {
    const panel = source('../components/CollectionTaskPanel.vue')
    const sidebar = source('../components/ParserSidebar.vue')
    const scriptEditor = source('../components/ScriptArtifactEditor.vue')
    const semantic = source('../components/SemanticResultPanel.vue')
    expect(panel).toContain('等待设备输出')
    expect(panel).toContain("props.readonly ? '请从记录列表选择记录' : '尚未下发采集任务'")
    expect(panel).toContain('证据查询失败，请重试')
    expect(panel).toContain('证据访问受限')
    expect(panel).toContain('库创建时间：')
    expect(panel).not.toContain('连接建立后，设备输出会实时保留在此区域')
    expect(panel).not.toContain('尚未载入采集记录，请从记录列表选择有效记录')
    expect(panel).not.toContain('填写连接参数和采集命令，然后连接并执行')
    expect(panel).not.toContain('输出达到服务端或界面展示上限')
    expect(panel).not.toContain('证据查询暂时失败')
    expect(panel).not.toContain('未提供原提交请求')
    expect(panel).not.toContain('非浏览器提交时间')
    expect(sidebar).toContain('未启用自动解析，可选已发布版本')
    expect(sidebar).toContain('未配置默认解析版本')
    expect(sidebar).toContain('按默认版本解析，不丢原始输出')
    expect(sidebar).toContain('固定使用所选版本')
    expect(sidebar).toContain('仅执行采集，不生成结构化结果')
    expect(sidebar).toContain('暂无已发布解析版本')
    expect(sidebar).toContain('兼容解析仅作用于当前命令块')
    expect(sidebar).not.toContain('平台未启用自动解析')
    expect(sidebar).not.toContain('本次采集仍会完整保留原始输出')
    expect(sidebar).not.toContain('按平台默认版本识别命令内容')
    expect(sidebar).not.toContain('本次任务固定使用所选版本')
    expect(sidebar).not.toContain('可稍后重试，或仅保留原始输出')
    expect(sidebar).not.toContain('不影响版本化结构解析')
    expect(scriptEditor).not.toContain('MVP 不伪造脚本列表')
    expect(semantic).toContain('暂无解析结果')
    expect(semantic).not.toContain('采集完成后自动显示结构化数据')
  })
  it('管理页副标题与提示压缩为短句，安全警示保留组件形态', () => {
    const settings = source('../views/management/SettingsManagementView.vue')
    const overview = source('../views/management/OverviewManagementView.vue')
    const records = source('../views/management/RecordsManagementView.vue')
    const tasks = source('../views/management/TasksManagementView.vue')
    const scripts = source('../views/management/ScriptsManagementView.vue')
    const parser = source('../views/management/ParserManagementView.vue')
    expect(settings).toContain('只读身份与能力视图')
    expect(settings).toContain('能力开关不代表实际授权')
    expect(settings).not.toContain('不显示 token、秘密、服务端配置或可写运行参数')
    expect(settings).not.toContain('能力开关不等于当前身份获准执行操作')
    expect(overview).toContain('仅统计授权范围内数据')
    expect(overview).not.toContain('不包含无权访问的数据')
    expect(records).toContain('授权范围历史检索')
    expect(records).not.toContain('未知历史字段不伪造')
    expect(tasks).toContain('采集、解析与到期通知分开管理')
    expect(tasks).not.toContain('停止查看不会取消设备执行')
    expect(scripts).toContain('仅展示授权引用的不可变版本')
    expect(scripts).toContain('仅内存一次性交接，不落盘')
    expect(scripts).not.toContain('安全读取与载入工作台是两个独立、显式操作')
    expect(scripts).not.toContain('不保存到浏览器存储，不写入 URL')
    expect(parser).toContain('草稿 → 验证 → 发布 → 激活')
    expect(parser).toContain('输入完整 ReleaseRequest JSON，上限 32 MiB')
    expect(parser).toContain('留空使用当前活动版本')
    expect(parser).not.toContain('变更始终保留并发绑定校验')
    expect(parser).not.toContain('caseId / inputContent / expectedResultJson')
    expect(parser).not.toContain('command-output-block/v1 输入示例')
  })
  it('管理页卡片头为语义标题 h2，形成 h1→h2→h3 正确层级', () => {
    const views = [
      '../views/management/OverviewManagementView.vue',
      '../views/management/RecordsManagementView.vue',
      '../views/management/TasksManagementView.vue',
      '../views/management/ScriptsManagementView.vue',
      '../views/management/SettingsManagementView.vue',
      '../views/management/ParserManagementView.vue'
    ]
    for (const view of views) {
      const sfc = source(view)
      expect(sfc, view).not.toMatch(/<template #header>[\s\S]{0,120}<strong>/)
    }
    const overview = source('../views/management/OverviewManagementView.vue')
    expect(overview).toContain('<h2>授权范围运行概况</h2>')
    expect(overview).toContain('<h2>近期采集')
    expect(overview).toContain('<h2>解析等待摘要')
    expect(source('../views/management/SettingsManagementView.vue')).toContain('<h2>当前身份与部署能力</h2>')
    expect(source('../views/management/ParserManagementView.vue')).toContain('<h2>日志类型与版本</h2>')
    expect(source('../views/management/ParserManagementView.vue')).toContain('<h2>解析运行环境</h2>')
  })
  it('状态中文化并保留未知原始值', () => {
    expect(statusLabel('SUCCEEDED')).toBe('成功')
    expect(statusLabel('WAITING')).toBe('等待中')
    expect(statusLabel('NEW_STATE')).toBe('NEW_STATE')
    expect(statusLabel(null)).toBe('未知')
    expect(statusTone('NEW_STATE')).toBe('info')
    expect(statusTone('FAILED')).toBe('danger')
  })
  it('缺失和非法时间不伪造，统一使用本地时区', () => {
    expect(formatLocalTime(null)).toBe('未记录')
    expect(formatLocalTime('')).toBe('未记录')
    expect(formatLocalTime('invalid')).toBe('无效时间')
    const date = new Date('2026-09-08T03:04:05Z')
    const pad = (n: number) => String(n).padStart(2, '0')
    expect(formatLocalTime(date.toISOString())).toBe(`${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`)
  })
})
