package com.dp.deviceops.adapter.persistence.jdbc;

import com.dp.deviceops.core.model.InspectionSchedule;
import com.dp.deviceops.core.port.InspectionSchedulePort;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.support.TransactionTemplate;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

/** JDBC-only schedule trigger store: it emits outbox rows and never touches SSH or credentials. */
public final class JdbcInspectionSchedulePort implements InspectionSchedulePort {
    private final JdbcClient jdbc; private final TransactionTemplate tx; private final ObjectMapper json;
    public JdbcInspectionSchedulePort(JdbcClient jdbc, TransactionTemplate tx, ObjectMapper json){this.jdbc=jdbc;this.tx=tx;this.json=json;}
    public InspectionSchedule upsert(InspectionSchedule s){return tx.execute(x->{int n=jdbc.sql("update device_ops_collection_schedule set project_hint=:p,device_key_hints=:d,script_key=:sk,script_version=:sv,cron=:c,timezone=:z,callback_uri=:u,enabled=:enabled,next_run_at=:next,revision=revision+1 where namespace=:n and project_key=:pk and schedule_key=:k").param("n",s.namespace()).param("pk",s.projectKey()).param("k",s.scheduleKey()).param("p",s.projectHint()).param("d",encode(s.deviceKeyHints())).param("sk",s.scriptKey()).param("sv",s.scriptVersion()).param("c",s.cron()).param("z",s.timezone()).param("u",s.callbackUri()).param("enabled",s.enabled()).param("next",s.nextRunAt()).update();if(n==0)jdbc.sql("insert into device_ops_collection_schedule(namespace,project_key,schedule_key,project_hint,device_key_hints,script_key,script_version,cron,timezone,callback_uri,enabled,next_run_at,last_status,revision) values(:n,:pk,:k,:p,:d,:sk,:sv,:c,:z,:u,false,:next,'CREATED',0)").param("n",s.namespace()).param("pk",s.projectKey()).param("k",s.scheduleKey()).param("p",s.projectHint()).param("d",encode(s.deviceKeyHints())).param("sk",s.scriptKey()).param("sv",s.scriptVersion()).param("c",s.cron()).param("z",s.timezone()).param("u",s.callbackUri()).param("next",s.nextRunAt()).update();return find(s.namespace(),s.projectKey(),s.scheduleKey()).orElseThrow();});}
    public Optional<InspectionSchedule> find(String n,String p,String k){List<InspectionSchedule> r=jdbc.sql("select * from device_ops_collection_schedule where namespace=:n and project_key=:p and schedule_key=:k").param("n",n).param("p",p).param("k",k).query((rs,row)->map(rs.getString("NAMESPACE"),rs.getString("PROJECT_KEY"),rs.getString("SCHEDULE_KEY"),rs.getString("PROJECT_HINT"),rs.getString("DEVICE_KEY_HINTS"),rs.getString("SCRIPT_KEY"),rs.getString("SCRIPT_VERSION"),rs.getString("CRON"),rs.getString("TIMEZONE"),rs.getString("CALLBACK_URI"),rs.getBoolean("ENABLED"),rs.getTimestamp("NEXT_RUN_AT"),rs.getTimestamp("LAST_RUN_AT"),rs.getString("LAST_STATUS"),rs.getLong("REVISION"))).list();return r.stream().findFirst();}
    public List<InspectionSchedule> list(String n,String p){return jdbc.sql("select * from device_ops_collection_schedule where namespace=:n and project_key=:p order by schedule_key").param("n",n).param("p",p).query((rs,row)->map(rs.getString("NAMESPACE"),rs.getString("PROJECT_KEY"),rs.getString("SCHEDULE_KEY"),rs.getString("PROJECT_HINT"),rs.getString("DEVICE_KEY_HINTS"),rs.getString("SCRIPT_KEY"),rs.getString("SCRIPT_VERSION"),rs.getString("CRON"),rs.getString("TIMEZONE"),rs.getString("CALLBACK_URI"),rs.getBoolean("ENABLED"),rs.getTimestamp("NEXT_RUN_AT"),rs.getTimestamp("LAST_RUN_AT"),rs.getString("LAST_STATUS"),rs.getLong("REVISION"))).list();}
    public void disable(String n,String p,String k){jdbc.sql("update device_ops_collection_schedule set enabled=false,lease_owner=null,lease_until=null,revision=revision+1 where namespace=:n and project_key=:p and schedule_key=:k").param("n",n).param("p",p).param("k",k).update();}
    public List<InspectionSchedule> claimDue(String worker,Instant now,Instant until,int limit){return tx.execute(x->{List<InspectionSchedule> due=jdbc.sql("select * from device_ops_collection_schedule where enabled=true and next_run_at<=:now and (lease_until is null or lease_until<:now) order by next_run_at limit :limit").param("now",now).param("limit",limit).query((rs,row)->map(rs.getString("NAMESPACE"),rs.getString("PROJECT_KEY"),rs.getString("SCHEDULE_KEY"),rs.getString("PROJECT_HINT"),rs.getString("DEVICE_KEY_HINTS"),rs.getString("SCRIPT_KEY"),rs.getString("SCRIPT_VERSION"),rs.getString("CRON"),rs.getString("TIMEZONE"),rs.getString("CALLBACK_URI"),rs.getBoolean("ENABLED"),rs.getTimestamp("NEXT_RUN_AT"),rs.getTimestamp("LAST_RUN_AT"),rs.getString("LAST_STATUS"),rs.getLong("REVISION"))).list();List<InspectionSchedule> claimed=new ArrayList<>();for(InspectionSchedule s:due)if(jdbc.sql("update device_ops_collection_schedule set lease_owner=:w,lease_until=:u where namespace=:n and project_key=:p and schedule_key=:k and revision=:r and enabled=true and (lease_until is null or lease_until<:now)").param("w",worker).param("u",until).param("n",s.namespace()).param("p",s.projectKey()).param("k",s.scheduleKey()).param("r",s.revision()).param("now",now).update()==1)claimed.add(s);return claimed;});}
    public void completeDue(InspectionSchedule s,String worker,Instant due,Instant next){tx.executeWithoutResult(x->{String id=sha(s.namespace()+":"+s.projectKey()+":"+s.scheduleKey()+":"+due);Map<String,Object> payload=Map.of("eventId",id,"scheduleKey",s.scheduleKey(),"projectKey",s.projectKey(),"projectHint",s.projectHint(),"deviceKeyHints",s.deviceKeyHints(),"script",Map.of("key",s.scriptKey(),"version",s.scriptVersion()),"dueAt",due.toString());jdbc.sql("insert into device_ops_outbox(event_id,aggregate_id,event_type,payload,attempt_count,next_attempt_at,destination) values(:id,:a,'SCHEDULE_DUE',:p,0,current_timestamp,:d)").param("id",id).param("a",s.scheduleKey()).param("p",encode(payload)).param("d",s.callbackUri()).update();int changed=jdbc.sql("update device_ops_collection_schedule set last_run_at=:due,last_status='SCHEDULE_DUE',next_run_at=:next,revision=revision+1,lease_owner=null,lease_until=null where namespace=:n and project_key=:p and schedule_key=:k and lease_owner=:w and revision=:r").param("due",due).param("next",next).param("n",s.namespace()).param("p",s.projectKey()).param("k",s.scheduleKey()).param("w",worker).param("r",s.revision()).update();if(changed!=1)throw new IllegalStateException("schedule lease lost");});}
    public void failDue(InspectionSchedule s,String worker,String status){int changed=jdbc.sql("update device_ops_collection_schedule set last_status=:status,lease_owner=null,lease_until=null where namespace=:n and project_key=:p and schedule_key=:k and lease_owner=:w and revision=:r").param("status",status).param("n",s.namespace()).param("p",s.projectKey()).param("k",s.scheduleKey()).param("w",worker).param("r",s.revision()).update();if(changed!=1)throw new IllegalStateException("schedule lease lost");}
    private InspectionSchedule map(String n,String p,String k,String hint,String devices,String sk,String sv,String cron,String zone,String callback,boolean enabled,Timestamp next,Timestamp last,String status,long rev){return new InspectionSchedule(n,p,k,hint,decode(devices),sk,sv,cron,zone,callback,enabled,next==null?null:next.toInstant(),last==null?null:last.toInstant(),status,rev);}
    private String encode(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException("schedule payload cannot be encoded",e);}} private List<String> decode(String value){try{return json.readValue(value,json.getTypeFactory().constructCollectionType(List.class,String.class));}catch(Exception e){throw new IllegalStateException("schedule hints cannot be decoded",e);}} private static String sha(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
