CREATE TABLE IF NOT EXISTS "system_users" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(30) NOT NULL,
    "password" varchar(100) NOT NULL DEFAULT '',
    "nickname" varchar(30) NOT NULL,
    "remark" varchar(500),
    "dept_id" bigint,
    "post_ids" varchar(255),
    "email" varchar(50) DEFAULT '',
    "mobile" varchar(11) DEFAULT '',
    "sex" tinyint DEFAULT 0,
    "avatar" varchar(512) DEFAULT '',
    "status" tinyint NOT NULL,
    "login_ip" varchar(50) DEFAULT '',
    "login_date" timestamp,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '用户表';

CREATE TABLE IF NOT EXISTS "system_dept" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(30) NOT NULL DEFAULT '',
    "parent_id" bigint NOT NULL DEFAULT 0,
    "sort" int NOT NULL DEFAULT 0,
    "leader_user_id" bigint,
    "phone" varchar(11),
    "email" varchar(50),
    "status" tinyint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '部门表';

CREATE TABLE IF NOT EXISTS "system_post" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(64) NOT NULL,
    "name" varchar(50) NOT NULL,
    "sort" int NOT NULL,
    "status" tinyint NOT NULL,
    "remark" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '岗位表';

CREATE TABLE IF NOT EXISTS "system_role" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(30) NOT NULL,
    "code" varchar(100) NOT NULL,
    "sort" int NOT NULL,
    "data_scope" tinyint NOT NULL DEFAULT 1,
    "data_scope_dept_ids" varchar(500) NOT NULL DEFAULT '',
    "status" tinyint NOT NULL,
    "type" tinyint NOT NULL,
    "remark" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '角色表';

CREATE TABLE IF NOT EXISTS "system_menu" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(50) NOT NULL,
    "permission" varchar(100) NOT NULL DEFAULT '',
    "type" tinyint NOT NULL,
    "sort" int NOT NULL DEFAULT 0,
    "parent_id" bigint NOT NULL DEFAULT 0,
    "path" varchar(200) DEFAULT '',
    "icon" varchar(100) DEFAULT '#',
    "component" varchar(255),
    "component_name" varchar(255),
    "status" tinyint NOT NULL,
    "visible" bit NOT NULL DEFAULT TRUE,
    "keep_alive" bit NOT NULL DEFAULT TRUE,
    "always_show" bit NOT NULL DEFAULT TRUE,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '菜单表';

CREATE TABLE IF NOT EXISTS "system_user_role" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL,
    "role_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '用户角色关联表';

CREATE TABLE IF NOT EXISTS "system_role_menu" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "role_id" bigint NOT NULL,
    "menu_id" bigint NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '角色菜单关联表';

CREATE TABLE IF NOT EXISTS "system_user_post" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" bigint NOT NULL DEFAULT 0,
    "post_id" bigint NOT NULL DEFAULT 0,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '用户岗位关联表';

CREATE TABLE IF NOT EXISTS "system_dict_type" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(100) NOT NULL DEFAULT '',
    "type" varchar(100) NOT NULL DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "remark" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "deleted_time" timestamp,
    PRIMARY KEY ("id")
) COMMENT '字典类型表';

CREATE TABLE IF NOT EXISTS "system_dict_data" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sort" int NOT NULL DEFAULT 0,
    "label" varchar(100) NOT NULL DEFAULT '',
    "value" varchar(100) NOT NULL DEFAULT '',
    "dict_type" varchar(100) NOT NULL DEFAULT '',
    "status" tinyint NOT NULL DEFAULT 0,
    "color_type" varchar(100) DEFAULT '',
    "css_class" varchar(100) DEFAULT '',
    "remark" varchar(500),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    PRIMARY KEY ("id")
) COMMENT '字典数据表';

CREATE TABLE IF NOT EXISTS "system_login_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "log_type" bigint NOT NULL,
    "trace_id" varchar(64) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL DEFAULT 0,
    "user_type" tinyint NOT NULL DEFAULT 0,
    "username" varchar(50) NOT NULL DEFAULT '',
    "result" tinyint NOT NULL,
    "user_ip" varchar(50) NOT NULL,
    "user_agent" varchar(512) NOT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '登录日志表';

CREATE TABLE IF NOT EXISTS "system_operate_log" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "trace_id" varchar(64) NOT NULL DEFAULT '',
    "user_id" bigint NOT NULL,
    "user_type" tinyint NOT NULL DEFAULT 0,
    "type" varchar(50) NOT NULL,
    "sub_type" varchar(50) NOT NULL,
    "biz_id" bigint NOT NULL,
    "action" varchar(2000) NOT NULL DEFAULT '',
    "success" bit NOT NULL DEFAULT TRUE,
    "extra" varchar(2000) NOT NULL DEFAULT '',
    "request_method" varchar(16) DEFAULT '',
    "request_url" varchar(255) DEFAULT '',
    "user_ip" varchar(50),
    "user_agent" varchar(512),
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT 0,
    PRIMARY KEY ("id")
) COMMENT '操作日志表';
CREATE TABLE IF NOT EXISTS "plt_business_code_rule" (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "rule_code" varchar(64) NOT NULL,
    "rule_version" varchar(32) NOT NULL,
    "prefix" varchar(32) NOT NULL,
    "padding_width" int NOT NULL,
    "next_value" bigint NOT NULL,
    "status" varchar(32) NOT NULL,
    "effective_from" timestamp NOT NULL,
    "effective_to" timestamp,
    "version" int NOT NULL DEFAULT 0,
    "creator" bigint,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "updater" bigint,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("tenant_id", "rule_code", "rule_version")
);

CREATE TABLE IF NOT EXISTS "plt_idempotency_record" (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "scope_code" varchar(64) NOT NULL,
    "actor_id" bigint NOT NULL,
    "idempotency_key" varchar(128) NOT NULL,
    "request_sha256" varchar(64) NOT NULL,
    "status" varchar(32) NOT NULL,
    "response_json" varchar(4000),
    "resource_id" bigint,
    "correlation_id" varchar(128),
    "version" int NOT NULL DEFAULT 0,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("tenant_id", "scope_code", "actor_id", "idempotency_key")
);

CREATE TABLE IF NOT EXISTS "plt_operation_audit" (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "actor_id" bigint,
    "operation_code" varchar(64) NOT NULL,
    "resource_type" varchar(64) NOT NULL,
    "resource_id" varchar(128),
    "decision_code" varchar(32) NOT NULL,
    "detail_json" varchar(4000) NOT NULL,
    "correlation_id" varchar(128),
    "operation_time" timestamp NOT NULL,
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "plt_outbox_event" (
    "id" bigint NOT NULL,
    "tenant_id" bigint NOT NULL,
    "event_id" varchar(128) NOT NULL,
    "aggregate_type" varchar(64) NOT NULL,
    "aggregate_id" varchar(128) NOT NULL,
    "event_type" varchar(128) NOT NULL,
    "event_version" int NOT NULL,
    "payload_json" varchar(4000) NOT NULL,
    "publish_status" varchar(32) NOT NULL,
    "retry_count" int NOT NULL DEFAULT 0,
    "next_retry_time" timestamp,
    "published_time" timestamp,
    "correlation_id" varchar(128),
    "create_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    "update_time" timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("event_id")
);
