CREATE TABLE it_declared_note (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 tenant_id BIGINT NOT NULL,
 version BIGINT NOT NULL DEFAULT 0,
 project_ref BIGINT NOT NULL,
 title VARCHAR(200) NOT NULL,
 amount DECIMAL(18,2) NULL,
 internal_memo VARCHAR(500) NULL,
 reference_code VARCHAR(100) NULL,
 tags JSON NULL,
 creator VARCHAR(64) NULL,
 create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updater VARCHAR(64) NULL,
 update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 deleted BIT(1) NOT NULL DEFAULT b'0'
) ENGINE=InnoDB;
