-- Current business rows do not carry version-management or form metadata.
CREATE TABLE sol_requirement_analysis (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    project_background LONGTEXT NULL,
    project_objective LONGTEXT NULL,
    network_topology LONGTEXT NULL,
    transmission_requirement LONGTEXT NULL,
    traffic_requirement LONGTEXT NULL,
    business_requirement LONGTEXT NULL,
    ip_planning LONGTEXT NULL,
    redundancy_requirement LONGTEXT NULL,
    security_protection LONGTEXT NULL,
    operations_requirement LONGTEXT NULL,
    logging_requirement LONGTEXT NULL,
    status_code VARCHAR(32) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ra_current_project (tenant_id, project_id)
);

-- Revision identity and all version metadata reside in the Owner's history table.
CREATE TABLE sol_requirement_analysis_revision (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    entity_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    revision_no INT NOT NULL,
    source_revision_id BIGINT NULL,
    base_effective_revision_id BIGINT NULL,
    base_entity_version INT NULL,
    revision_state VARCHAR(16) NOT NULL,
    draft_marker TINYINT NULL,
    effective_marker TINYINT NULL,
    change_reason VARCHAR(2000) NULL,
    frozen_by BIGINT NULL,
    frozen_at DATETIME(3) NULL,
    project_template_id BIGINT NULL,
    project_template_revision_id BIGINT NULL,
    execution_snapshot JSON NULL COMMENT 'Immutable project binding provenance; not form configuration or business content',
    project_background LONGTEXT NULL,
    project_objective LONGTEXT NULL,
    network_topology LONGTEXT NULL,
    transmission_requirement LONGTEXT NULL,
    traffic_requirement LONGTEXT NULL,
    business_requirement LONGTEXT NULL,
    ip_planning LONGTEXT NULL,
    redundancy_requirement LONGTEXT NULL,
    security_protection LONGTEXT NULL,
    operations_requirement LONGTEXT NULL,
    logging_requirement LONGTEXT NULL,
    status_code VARCHAR(32) NOT NULL,
    version INT NOT NULL DEFAULT 1,
    creator VARCHAR(64) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_ra_revision (tenant_id, entity_id, revision_no),
    UNIQUE KEY uk_ra_project_revision (tenant_id, project_id, revision_no),
    UNIQUE KEY uk_ra_draft (tenant_id, project_id, draft_marker),
    UNIQUE KEY uk_ra_effective (tenant_id, project_id, effective_marker),
    CONSTRAINT ck_ra_revision_state CHECK (
        (revision_state = 'DRAFT' AND draft_marker = 1 AND effective_marker IS NULL AND frozen_at IS NULL AND frozen_by IS NULL)
        OR (revision_state = 'FROZEN' AND draft_marker IS NULL AND frozen_at IS NOT NULL AND frozen_by IS NOT NULL)),
    CONSTRAINT ck_ra_effective CHECK (effective_marker IS NULL OR effective_marker = 1),
    CONSTRAINT ck_ra_revision_no CHECK (revision_no > 0)
);

CREATE TABLE plt_entity_extension_definition (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_module VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    revision_no INT NOT NULL,
    source_form_revision_id BIGINT NULL,
    fields_json JSON NOT NULL,
    creator VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL DEFAULT '',
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_entity_extension_definition (tenant_id, owner_module, entity_type, revision_no),
    UNIQUE KEY uk_entity_definition_source (tenant_id, owner_module, entity_type, source_form_revision_id)
);

CREATE TABLE plt_entity_extension_value (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_module VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id BIGINT NOT NULL,
    revision_id BIGINT NOT NULL DEFAULT 0 COMMENT '0=current; positive=Owner history record ID',
    definition_revision_id BIGINT NOT NULL,
    values_json JSON NOT NULL,
    version INT NOT NULL DEFAULT 1,
    creator VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL,
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_entity_extension_target (tenant_id, owner_module, entity_type, entity_id, revision_id),
    CONSTRAINT fk_extension_definition FOREIGN KEY (definition_revision_id) REFERENCES plt_entity_extension_definition(id)
);

CREATE TABLE plt_entity_form_binding (
    id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    owner_module VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id BIGINT NOT NULL,
    revision_id BIGINT NOT NULL DEFAULT 0 COMMENT '0=current; positive=Owner history record ID',
    form_revision_id BIGINT NOT NULL,
    extension_definition_revision_id BIGINT NULL,
    field_bindings_json JSON NOT NULL COMMENT 'Control field key to stable business/extension field code',
    version INT NOT NULL DEFAULT 1,
    creator VARCHAR(64) NOT NULL,
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updater VARCHAR(64) NOT NULL,
    update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    deleted BIT(1) NOT NULL DEFAULT b'0',
    PRIMARY KEY (id),
    UNIQUE KEY uk_entity_form_target (tenant_id, owner_module, entity_type, entity_id, revision_id)
);
