package cn.iocoder.yudao.module.system.service.permission;
import cn.iocoder.yudao.module.system.dal.mysql.permission.*;
import cn.iocoder.yudao.module.system.dal.redis.RedisKeyConstants;
import org.junit.jupiter.api.*;
import org.springframework.context.annotation.*;
import org.springframework.cache.annotation.EnableCaching;
import org.springframework.cache.CacheManager;
import org.springframework.jdbc.datasource.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionSynchronizationManager;
import javax.sql.DataSource;
import cn.iocoder.yudao.module.system.service.user.AdminUserServiceImpl;
import cn.iocoder.yudao.module.system.dal.mysql.user.AdminUserMapper;
import cn.iocoder.yudao.module.system.dal.mysql.dept.UserPostMapper;
import cn.iocoder.yudao.module.system.dal.dataobject.user.AdminUserDO;
import org.springframework.test.util.ReflectionTestUtils;
import java.util.List;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
@org.junit.jupiter.api.condition.EnabledIfSystemProperty(named="permission.association.redis",matches="true")
class PermissionAssociationRedisProtectionTest {
 @Configuration @EnableCaching @EnableTransactionManagement(proxyTargetClass=true)
 static class Config {
  @Bean DataSource dataSource(){return new DriverManagerDataSource("jdbc:h2:mem:associationRedisB14;DB_CLOSE_DELAY=-1","sa","");}
  @Bean PlatformTransactionManager transactionManager(DataSource ds){return new DataSourceTransactionManager(ds);}
  @Bean org.redisson.spring.data.connection.RedissonConnectionFactory redisConnectionFactory(){var config=new org.redisson.config.Config();config.setThreads(2).setNettyThreads(2);config.useSingleServer().setAddress("redis://127.0.0.1:25579");return new org.redisson.spring.data.connection.RedissonConnectionFactory(config);}
  @Bean org.springframework.data.redis.core.RedisTemplate<String,Object> redisTemplate(org.redisson.spring.data.connection.RedissonConnectionFactory factory){var t=new org.springframework.data.redis.core.RedisTemplate<String,Object>();t.setConnectionFactory(factory);return t;}
  @Bean CacheManager cacheManager(org.springframework.data.redis.core.RedisTemplate<String,Object> template){var props=new cn.iocoder.yudao.framework.tenant.config.TenantProperties();props.setIgnoreCaches(java.util.Set.of(RedisKeyConstants.USER_ROLE_ID_LIST));return new cn.iocoder.yudao.framework.tenant.config.YudaoTenantAutoConfiguration().tenantRedisCacheManager(template,new cn.iocoder.yudao.framework.redis.config.YudaoCacheAutoConfiguration().redisCacheConfiguration(new org.springframework.boot.cache.autoconfigure.CacheProperties()),new cn.iocoder.yudao.framework.redis.config.YudaoCacheProperties(),props);}
  @Bean cn.hutool.extra.spring.SpringUtil springUtil(){return new cn.hutool.extra.spring.SpringUtil();}
  @Bean RoleService roleService(){return mock(RoleService.class);}
  @Bean MenuService menuService(){return mock(MenuService.class);}
  @Bean PermissionServiceImpl permissions(){return new PermissionServiceImpl();}
  @Bean cn.iocoder.yudao.module.system.service.dept.DeptService deptService(){return mock(cn.iocoder.yudao.module.system.service.dept.DeptService.class);}
  @Bean cn.iocoder.yudao.module.system.service.dept.PostService postService(){return mock(cn.iocoder.yudao.module.system.service.dept.PostService.class);}
  @Bean org.springframework.security.crypto.password.PasswordEncoder passwordEncoder(){return mock(org.springframework.security.crypto.password.PasswordEncoder.class);}
  @Bean cn.iocoder.yudao.module.system.service.tenant.TenantService tenantService(){return mock(cn.iocoder.yudao.module.system.service.tenant.TenantService.class);}
  @Bean cn.iocoder.yudao.module.system.service.oauth2.OAuth2TokenService oauth2TokenService(){return mock(cn.iocoder.yudao.module.system.service.oauth2.OAuth2TokenService.class);}
  @Bean cn.iocoder.yudao.module.infra.api.config.ConfigApi configApi(){return mock(cn.iocoder.yudao.module.infra.api.config.ConfigApi.class);}
  @Bean cn.iocoder.yudao.module.system.mq.producer.user.AdminUserProducer adminUserProducer(){return mock(cn.iocoder.yudao.module.system.mq.producer.user.AdminUserProducer.class);}
  @Bean AdminUserMapper adminUserMapper(){return mock(AdminUserMapper.class);}
  @Bean UserPostMapper userPostMapper(){return mock(UserPostMapper.class);}
  @Bean AdminUserServiceImpl adminUsers(AdminUserMapper users,UserPostMapper posts,PermissionAssociationService associations){var service=new AdminUserServiceImpl();ReflectionTestUtils.setField(service,"userMapper",users);ReflectionTestUtils.setField(service,"userPostMapper",posts);ReflectionTestUtils.setField(service,"permissionService",associations);return service;}
  @Bean RoleMenuMapper roleMenuMapper(){return mock(RoleMenuMapper.class);}
  @Bean UserRoleMapper userRoleMapper(){return mock(UserRoleMapper.class);}
  @Bean PermissionAssociationService associations(RoleMenuMapper rm,UserRoleMapper ur){return new PermissionAssociationService(rm,ur);}
 }
 AnnotationConfigApplicationContext context;JdbcTemplate jdbc;PermissionAssociationService service;RoleMenuMapper rm;UserRoleMapper ur;CacheManager caches;
 @BeforeEach void setup(org.junit.jupiter.api.TestInfo info){System.out.println("START "+info.getDisplayName()+" thread="+Thread.currentThread().getName());cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.setTenantId(1L);context=new AnnotationConfigApplicationContext(Config.class);try(var c=context.getBean(org.redisson.spring.data.connection.RedissonConnectionFactory.class).getConnection()){c.serverCommands().flushDb();}jdbc=new JdbcTemplate(context.getBean(DataSource.class));jdbc.execute("CREATE TABLE IF NOT EXISTS test_association(kind VARCHAR(8),id BIGINT)");jdbc.update("DELETE FROM test_association");jdbc.update("INSERT INTO test_association VALUES('UR',9),('RM',9)");service=context.getBean(PermissionAssociationService.class);rm=context.getBean(RoleMenuMapper.class);ur=context.getBean(UserRoleMapper.class);caches=context.getBean(CacheManager.class);}
 @AfterEach void close(){try(var c=context.getBean(org.redisson.spring.data.connection.RedissonConnectionFactory.class).getConnection()){System.out.println("RAW_KEYS "+c.keyCommands().keys("*".getBytes()).stream().map(String::new).toList()+" tx="+TransactionSynchronizationManager.isActualTransactionActive());}context.close();cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.clear();}
 void seedCache(){for(String name:new String[]{RedisKeyConstants.MENU_ROLE_ID_LIST,RedisKeyConstants.USER_ROLE_ID_LIST}){caches.getCache(name).put(9L,"stale");caches.getCache(name).put(10L,"other");awaitWarm(caches.getCache(name),9L);awaitWarm(caches.getCache(name),10L);}}
 @Test void roleDeletionCommitsBothRelationsAndEvictsBothCaches(){seedCache();doAnswer(x->{assertTrue(TransactionSynchronizationManager.isActualTransactionActive());return jdbc.update("DELETE FROM test_association WHERE kind='UR' AND id=9");}).when(ur).deleteListByRoleId(9L);doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='RM' AND id=9")).when(rm).deleteListByRoleId(9L);service.processRoleDeleted(9L);assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));for(String name:new String[]{RedisKeyConstants.MENU_ROLE_ID_LIST,RedisKeyConstants.USER_ROLE_ID_LIST}){assertNull(caches.getCache(name).get(9L));assertNull(caches.getCache(name).get(10L));}assertFalse(TransactionSynchronizationManager.isActualTransactionActive());}
 @Test void failedRoleCleanupRollsBackFirstSqlAndRetainsCache(){seedCache();doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='UR' AND id=9")).when(ur).deleteListByRoleId(9L);doThrow(new IllegalStateException("synthetic second write failure")).when(rm).deleteListByRoleId(9L);assertThrows(IllegalStateException.class,()->service.processRoleDeleted(9L));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));}
 @Test void menuCleanupEvictsOnlyTargetMenu(){seedCache();service.processMenuDeleted(9L);verify(rm).deleteListByMenuId(9L);assertNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(10L));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));}
 @Test void userCleanupEvictsOnlyTargetUser(){seedCache();service.processUserDeleted(9L);verify(ur).deleteListByUserId(9L);assertNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(10L));assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));}
 @Test void userDeletionCommitsUserRoleAndPostSql(){var users=context.getBean(AdminUserMapper.class);var posts=context.getBean(UserPostMapper.class);jdbc.update("INSERT INTO test_association VALUES('USER',9),('POST',9)");when(users.selectById(9L)).thenReturn(new AdminUserDO().setId(9L));doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='USER' AND id=9")).when(users).deleteById(9L);doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='UR' AND id=9")).when(ur).deleteListByUserId(9L);doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='POST' AND id=9")).when(posts).deleteByUserId(9L);context.getBean(AdminUserServiceImpl.class).deleteUser(9L);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));assertEquals("RM",jdbc.queryForObject("SELECT kind FROM test_association",String.class));}
 @Test void userAssociationFailureRollsBackUserDeletion(){var users=context.getBean(AdminUserMapper.class);var posts=context.getBean(UserPostMapper.class);jdbc.update("INSERT INTO test_association VALUES('USER',9)");when(users.selectById(9L)).thenReturn(new AdminUserDO().setId(9L));doAnswer(x->{assertTrue(TransactionSynchronizationManager.isActualTransactionActive());return jdbc.update("DELETE FROM test_association WHERE kind='USER' AND id=9");}).when(users).deleteById(9L);doThrow(new IllegalStateException("synthetic cleanup failure")).when(ur).deleteListByUserId(9L);assertThrows(IllegalStateException.class,()->context.getBean(AdminUserServiceImpl.class).deleteUser(9L));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM test_association WHERE kind='USER'",Integer.class));verifyNoInteractions(posts);}
 @Test void batchCleanupFailureRollsBackEarlierUserAndRelations(){var users=context.getBean(AdminUserMapper.class);var posts=context.getBean(UserPostMapper.class);jdbc.update("INSERT INTO test_association VALUES('USER',9),('USER',10),('POST',9)");doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='USER'")).when(users).deleteByIds(List.of(9L,10L));doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='UR' AND id=9")).when(ur).deleteListByUserId(9L);doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='POST' AND id=9")).when(posts).deleteByUserId(9L);doThrow(new IllegalStateException("synthetic second user failure")).when(ur).deleteListByUserId(10L);assertThrows(IllegalStateException.class,()->context.getBean(AdminUserServiceImpl.class).deleteUserList(List.of(9L,10L)));assertEquals(5,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));}


 @Test void committedKeysExistInRealRedisAndUserRevokeRemovesOnlyTarget(){seedCache();try(var c=context.getBean(org.redisson.spring.data.connection.RedissonConnectionFactory.class).getConnection()){assertTrue(c.keyCommands().exists((RedisKeyConstants.USER_ROLE_ID_LIST+":9").getBytes()));assertTrue(c.keyCommands().exists((RedisKeyConstants.MENU_ROLE_ID_LIST+":1:9").getBytes()));}service.processUserDeleted(9L);assertNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(10L));}
 @Test void menuEvictionWaitsForCommitAndRollbackKeepsSqlAndRedis(){seedCache();doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='RM' AND id=9")).when(rm).deleteListByMenuId(9L);var tx=new org.springframework.transaction.support.TransactionTemplate(context.getBean(PlatformTransactionManager.class));assertThrows(IllegalStateException.class,()->tx.execute(status->{service.processMenuDeleted(9L);assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));throw new IllegalStateException("synthetic outer failure after association return");}));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));tx.execute(status->{service.processMenuDeleted(9L);assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));return null;});assertNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L));}
 @Test void adminUserFailureAfterAssociationReturnRetainsWarmRedis(){seedCache();var users=context.getBean(AdminUserMapper.class);var posts=context.getBean(UserPostMapper.class);jdbc.update("INSERT INTO test_association VALUES('USER',9)");when(users.selectById(9L)).thenReturn(new AdminUserDO().setId(9L));doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='USER' AND id=9")).when(users).deleteById(9L);doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='UR' AND id=9")).when(ur).deleteListByUserId(9L);doThrow(new IllegalStateException("synthetic post failure after cache eviction queued")).when(posts).deleteByUserId(9L);assertThrows(IllegalStateException.class,()->context.getBean(AdminUserServiceImpl.class).deleteUser(9L));assertEquals(3,jdbc.queryForObject("SELECT COUNT(*) FROM test_association",Integer.class));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));}
 @Test void roleDeletionClearsCurrentTenantMenuButPreservesOtherTenantMenu(){seedCache();cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.setTenantId(2L);caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).put(9L,"tenant2");awaitWarm(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST),9L);assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L));cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.setTenantId(1L);service.processRoleDeleted(9L);assertNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L),"tenant1 menu cache must be empty immediately after role deletion");cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.setTenantId(2L);assertEquals("tenant2",caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(9L).get());assertNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(9L),"global user-role cache must be empty immediately after role deletion");}
 @Test void productionPermissionReaderDeniesDisabledAndRevokedRolesAfterRedisEviction(){
  jdbc.execute("CREATE TABLE IF NOT EXISTS permission_fixture(tenant BIGINT,user_id BIGINT,role_id BIGINT,menu_id BIGINT,status INT)");jdbc.update("DELETE FROM permission_fixture");jdbc.update("INSERT INTO permission_fixture VALUES(1,91,19,29,0),(2,92,20,29,0)");
  when(ur.selectListByUserId(anyLong())).thenAnswer(x->jdbc.query("SELECT role_id FROM permission_fixture WHERE user_id=? AND tenant=?",(rs,n)->new cn.iocoder.yudao.module.system.dal.dataobject.permission.UserRoleDO().setUserId(x.getArgument(0)).setRoleId(rs.getLong(1)),x.getArgument(0),cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId()));
  when(rm.selectListByMenuId(29L)).thenAnswer(x->jdbc.query("SELECT role_id FROM permission_fixture WHERE menu_id=29 AND tenant=?",(rs,n)->new cn.iocoder.yudao.module.system.dal.dataobject.permission.RoleMenuDO().setMenuId(29L).setRoleId(rs.getLong(1)),cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId()));
  when(context.getBean(RoleService.class).getRoleListFromCache(anyCollection())).thenAnswer(x->{java.util.List<cn.iocoder.yudao.module.system.dal.dataobject.permission.RoleDO> rows=new java.util.ArrayList<>();for(Long id:(java.util.Collection<Long>)x.getArgument(0))rows.addAll(jdbc.query("SELECT status FROM permission_fixture WHERE role_id=? AND tenant=?",(rs,n)->new cn.iocoder.yudao.module.system.dal.dataobject.permission.RoleDO().setId(id).setCode("custom").setStatus(rs.getInt(1)),id,cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId()));return rows;});
  when(context.getBean(MenuService.class).getMenuIdListByPermissionFromCache("fixture:read")).thenReturn(List.of(29L));var p=context.getBean(PermissionServiceImpl.class);assertTrue(p.hasAnyPermissions(91L,"fixture:read"));assertNotNull(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST).get(91L));assertNotNull(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).get(29L));
  jdbc.update("UPDATE permission_fixture SET status=1 WHERE tenant=1");assertFalse(p.hasAnyPermissions(91L,"fixture:read"));jdbc.update("UPDATE permission_fixture SET status=0 WHERE tenant=1");assertTrue(p.hasAnyPermissions(91L,"fixture:read"));
  doAnswer(x->jdbc.update("DELETE FROM permission_fixture WHERE tenant=? AND user_id=?",cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.getRequiredTenantId(),x.getArgument(0))).when(ur).deleteListByUserId(91L);service.processUserDeleted(91L);assertFalse(p.hasAnyPermissions(91L,"fixture:read"));
  cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder.setTenantId(2L);assertTrue(p.hasAnyPermissions(92L,"fixture:read"));doAnswer(x->jdbc.update("UPDATE permission_fixture SET menu_id=NULL WHERE tenant=2 AND menu_id=29")).when(rm).deleteListByMenuId(29L);service.processMenuDeleted(29L);assertFalse(p.hasAnyPermissions(92L,"fixture:read"));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM permission_fixture WHERE tenant=2",Integer.class));
 }


 @Test void repeatedMenuRevocationMustDenyImmediatelyInProductionPermissionReader() throws Exception {
  when(ur.selectListByUserId(91L)).thenReturn(List.of(new cn.iocoder.yudao.module.system.dal.dataobject.permission.UserRoleDO().setUserId(91L).setRoleId(19L)));
  when(rm.selectListByMenuId(9L)).thenAnswer(x->jdbc.query("SELECT id FROM test_association WHERE kind='RM' AND id=9",(rs,n)->new cn.iocoder.yudao.module.system.dal.dataobject.permission.RoleMenuDO().setMenuId(9L).setRoleId(19L)));
  when(context.getBean(RoleService.class).getRoleListFromCache(anyCollection())).thenReturn(new java.util.ArrayList<>(List.of(new cn.iocoder.yudao.module.system.dal.dataobject.permission.RoleDO().setId(19L).setCode("custom").setStatus(0))));
  when(context.getBean(MenuService.class).getMenuIdListByPermissionFromCache("fixture:read")).thenReturn(List.of(9L));doAnswer(x->jdbc.update("DELETE FROM test_association WHERE kind='RM' AND id=9")).when(rm).deleteListByMenuId(9L);var permissions=context.getBean(PermissionServiceImpl.class);int stale=0;
  for(int i=0;i<100;i++){jdbc.update("DELETE FROM test_association WHERE kind='RM'");jdbc.update("INSERT INTO test_association VALUES('RM',9)");caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST).evictIfPresent(9L);assertTrue(permissions.hasAnyPermissions(91L,"fixture:read"));awaitWarm(caches.getCache(RedisKeyConstants.USER_ROLE_ID_LIST),91L);awaitWarm(caches.getCache(RedisKeyConstants.MENU_ROLE_ID_LIST),9L);service.processMenuDeleted(9L);if(permissions.hasAnyPermissions(91L,"fixture:read"))stale++;long deadline=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(2);while(permissions.hasAnyPermissions(91L,"fixture:read")&&System.nanoTime()<deadline)Thread.sleep(1);assertFalse(permissions.hasAnyPermissions(91L,"fixture:read"));}
  System.out.println("REVOKE_RESULT attempts=100 immediateStaleAuthorization="+stale+" eventualDenied=100");assertEquals(0,stale,"Deleted menu association must not grant permission after command returns");
 }


 void awaitWarm(org.springframework.cache.Cache cache,Long key){long deadline=System.nanoTime()+java.util.concurrent.TimeUnit.SECONDS.toNanos(2);while(cache.get(key)==null&&System.nanoTime()<deadline)java.util.concurrent.locks.LockSupport.parkNanos(1000000);assertNotNull(cache.get(key),"Redis warm-up must be acknowledged before deletion");}

}
