CREATE TABLE device_ops_collection_command_output (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT NOT NULL,
    command_index INTEGER NOT NULL,
    command_text CLOB NOT NULL,
    status VARCHAR(24) NOT NULL,
    standard_output CLOB NOT NULL,
    standard_error CLOB NOT NULL,
    received_bytes BIGINT NOT NULL DEFAULT 0,
    page_count INTEGER NOT NULL DEFAULT 0,
    output_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    exit_code INTEGER,
    outcome_message VARCHAR(500),
    parsed_facts_json CLOB NOT NULL,
    parse_warnings_json CLOB NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    legacy_record BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_device_ops_command_output UNIQUE (target_id, command_index),
    CONSTRAINT fk_device_ops_command_output_target
        FOREIGN KEY (target_id) REFERENCES device_ops_collection_target(id),
    CONSTRAINT ck_device_ops_command_output_index CHECK (command_index > 0)
);

CREATE INDEX idx_device_ops_command_output_target
    ON device_ops_collection_command_output(target_id, command_index);

ALTER TABLE device_ops_collection_output_event
    ADD COLUMN command_index INTEGER;

CREATE INDEX idx_device_ops_output_target_command_sequence
    ON device_ops_collection_output_event(target_id, command_index, sequence_no);
