CREATE TABLE device_ops_script (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namespace VARCHAR(100) NOT NULL,
    script_key VARCHAR(200) NOT NULL,
    source VARCHAR(40) NOT NULL,
    CONSTRAINT uk_device_ops_script_namespace_key UNIQUE (namespace, script_key)
);

CREATE TABLE device_ops_script_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    script_id BIGINT NOT NULL,
    version VARCHAR(100) NOT NULL,
    content CLOB NOT NULL,
    sha256 CHAR(64) NOT NULL,
    parser_type VARCHAR(100) NOT NULL,
    parser_config CLOB,
    CONSTRAINT uk_device_ops_script_version UNIQUE (script_id, version),
    CONSTRAINT fk_device_ops_script_version_script FOREIGN KEY (script_id) REFERENCES device_ops_script (id)
);
