CREATE TABLE device_ops_collection (
    task_id VARCHAR(100) PRIMARY KEY,
    namespace VARCHAR(100) NOT NULL,
    project_key VARCHAR(200) NOT NULL,
    external_request_id VARCHAR(200),
    idempotency_key VARCHAR(200) NOT NULL,
    activity_type VARCHAR(100),
    callback_uri VARCHAR(2000),
    script_source VARCHAR(40) NOT NULL,
    script_key VARCHAR(200) NOT NULL,
    script_version VARCHAR(100) NOT NULL,
    script_content CLOB NOT NULL,
    script_sha256 CHAR(64) NOT NULL,
    script_policy VARCHAR(40) NOT NULL,
    parser_type VARCHAR(100) NOT NULL,
    parser_config CLOB,
    CONSTRAINT uk_device_ops_collection_idempotency UNIQUE (namespace, idempotency_key),
    CONSTRAINT uk_device_ops_collection_external_request UNIQUE (namespace, external_request_id)
);

CREATE TABLE device_ops_collection_target (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL,
    project_name VARCHAR(500) NOT NULL,
    project_code VARCHAR(200) NOT NULL,
    device_key VARCHAR(200) NOT NULL,
    device_name VARCHAR(500) NOT NULL,
    vendor VARCHAR(200) NOT NULL,
    model VARCHAR(200) NOT NULL,
    extensions_json CLOB NOT NULL,
    host VARCHAR(500) NOT NULL,
    port INTEGER NOT NULL,
    username VARCHAR(500) NOT NULL,
    host_key_fingerprint VARCHAR(1000),
    status VARCHAR(40) NOT NULL,
    standard_output CLOB NOT NULL,
    standard_error CLOB NOT NULL,
    exit_code INTEGER,
    outcome_message CLOB,
    output_truncated BOOLEAN NOT NULL,
    CONSTRAINT fk_device_ops_collection_target_task FOREIGN KEY (task_id) REFERENCES device_ops_collection (task_id)
);

CREATE TABLE device_ops_collection_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id BIGINT NOT NULL,
    attempt_no INTEGER NOT NULL,
    status VARCHAR(40) NOT NULL,
    lease_owner VARCHAR(200),
    lease_until TIMESTAMP,
    started_at TIMESTAMP,
    finished_at TIMESTAMP,
    failure_reason CLOB,
    CONSTRAINT uk_device_ops_attempt_number UNIQUE (target_id, attempt_no),
    CONSTRAINT fk_device_ops_attempt_target FOREIGN KEY (target_id) REFERENCES device_ops_collection_target (id)
);

CREATE TABLE device_ops_outbox (
    event_id VARCHAR(100) PRIMARY KEY,
    aggregate_id VARCHAR(100) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    payload CLOB NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL,
    delivered_at TIMESTAMP,
    last_error CLOB
);
