package cn.iocoder.yudao.module.pms.engineering.service.training;
import cn.iocoder.yudao.framework.tenant.core.context.TenantContextHolder;import cn.iocoder.yudao.framework.security.core.util.SecurityFrameworkUtils;
import cn.iocoder.yudao.module.pms.engineering.dal.dataobject.training.*;import cn.iocoder.yudao.module.pms.engineering.dal.mysql.training.*;import cn.iocoder.yudao.module.pms.engineering.dal.mysql.training.query.*;
import cn.iocoder.yudao.module.pms.platform.api.file.dto.*;import cn.iocoder.yudao.module.pms.project.api.scope.ProjectScopeApi;import cn.iocoder.yudao.module.pms.project.api.scope.dto.*;import cn.iocoder.yudao.module.pms.project.api.acceptance.ProjectAcceptanceContextApi;import cn.iocoder.yudao.module.system.api.permission.PermissionApi;
import org.junit.jupiter.api.*;import java.time.LocalDateTime;import java.util.*;import static org.mockito.Mockito.*;import static org.mockito.ArgumentMatchers.*;import static org.junit.jupiter.api.Assertions.*;
class TrainingConfirmationGrantServiceTest {
 TrainingMapper training=mock(TrainingMapper.class);TrainingConfirmationGrantMapper grants=mock(TrainingConfirmationGrantMapper.class);PermissionApi permissions=mock(PermissionApi.class);ProjectScopeApi scopes=mock(ProjectScopeApi.class);ProjectAcceptanceContextApi projects=mock(ProjectAcceptanceContextApi.class);
 TrainingConfirmationGrantService service=new TrainingConfirmationGrantService(training,grants,permissions,scopes,projects);TrainingDO row;TrainingConfirmationGrantDO grant;
 @BeforeEach void setup(){TenantContextHolder.setTenantId(7L);org.springframework.security.core.context.SecurityContextHolder.clearContext();row=new TrainingDO();row.setId(9L);row.setTenantId(7L);row.setProjectId(20L);row.setStatus(1);row.setVersion(4L);row.setTrainerUserId(99L);row.setSignTokenDigest("a".repeat(64));row.setTokenExpiresAt(LocalDateTime.now().plusDays(7).withNano(0));row.setConfirmationRevisionId(101L);row.setConfirmationFormRules("{\"published\":true}");grant=new TrainingConfirmationGrantDO();grant.setId(71L);grant.setTenantId(7L);grant.setTrainingId(9L);grant.setIssuanceVersion(1L);grant.setIssuedByUserId(33L);grant.setIssuedAt(LocalDateTime.now().minusHours(1));grant.setExpiresAt(row.getTokenExpiresAt());grant.setScopeVersion(3L);grant.setConfirmationRevisionId(101L);grant.setConfirmationRulesSha256(org.apache.commons.codec.digest.DigestUtils.sha256Hex(row.getConfirmationFormRules()));when(training.selectFileOwnerForUpdate(new TrainingFileOwnerQuery(7L,9L))).thenReturn(row);when(grants.selectCurrentGrant(new TrainingConfirmationGrantQuery(7L,9L,row.getSignTokenDigest()))).thenReturn(grant);}
 @AfterEach void clear(){TenantContextHolder.clear();org.springframework.security.core.context.SecurityContextHolder.clearContext();}
 BusinessGrantGeneratedFilePolicyQuery q(){return new BusinessGrantGeneratedFilePolicyQuery(7L,"IMP","TRAINING_RECORD",9L,4L,71L,1L,"TRAINING_RECORD_HTML/4",null);}
 void allow(long actor){when(permissions.hasAnyPermissions(actor,"pms:imp-training:issue")).thenReturn(true);var scope=new ProjectScopeResult(20L,3L,Set.of(20L),Set.of());when(scopes.resolveCurrent(any())).thenReturn(scope);when(scopes.lockAndRevalidate(any())).thenReturn(scope);var project=new ProjectAcceptanceContextApi.Context(20L,20L,2L,3L,"ACTIVE");when(projects.inspect(any())).thenReturn(project);when(projects.lock(any(),eq(2L),eq(3L))).thenReturn(project);}
 @Test void anonymousCustomerUsesImmutableIssuerNotTrainerOrLoggedEmployee(){allow(33);var policy=service.lockAndRevalidate(q());assertNull(SecurityFrameworkUtils.getLoginUserId());assertEquals(33L,policy.executionUserId());verify(scopes).resolveCurrent(new ProjectCurrentScopeQuery(7L,33L,20L,ProjectScopeApi.ACTION_MANAGE));}
 @Test void missingHistoricalGrantNeverInventsIssuer(){when(grants.selectCurrentGrant(any())).thenReturn(null);assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(permissions);}
 @Test void expiredGrantRejected(){grant.setExpiresAt(LocalDateTime.now().minusMinutes(1));assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(permissions);}
 @Test void reissuedDigestDoesNotReuseEarlierGrant(){when(grants.selectCurrentGrant(any())).thenReturn(null);row.setSignTokenDigest("b".repeat(64));assertThrows(Exception.class,()->service.lockAndRevalidate(q()));}
 @Test void changedFrozenFormRejected(){row.setConfirmationFormRules("{\"published\":false}");assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(permissions);}
 @Test void staleRootVersionAndConfirmedReplayRejected(){row.setVersion(5L);assertThrows(Exception.class,()->service.lockAndRevalidate(q()));row.setVersion(4L);row.setStatus(2);assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(permissions);}
 @Test void foreignTenantGrantRejected(){grant.setTenantId(8L);assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(permissions);}
 @Test void revokedIssuerPermissionRejected(){assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verifyNoInteractions(scopes);}
 @Test void changedScopeRejectedBeforePhysicalFile(){allow(33);when(scopes.resolveCurrent(any())).thenReturn(new ProjectScopeResult(20L,4L,Set.of(20L),Set.of()));assertThrows(Exception.class,()->service.lockAndRevalidate(q()));verify(scopes,never()).lockAndRevalidate(any());}
 @Test void scopeRevocationToEmptyIsNotAnUnrestrictedGrant(){allow(33);when(scopes.lockAndRevalidate(any())).thenReturn(new ProjectScopeResult(20L,3L,Set.of(),Set.of(20L)));assertThrows(Exception.class,()->service.lockAndRevalidate(q()));}
 @Test void nativePurposeCannotBeChangedToPdfOrOtherOwner(){assertThrows(Exception.class,()->service.lockAndRevalidate(new BusinessGrantGeneratedFilePolicyQuery(7L,"IMP","TRAINING_RECORD",9L,4L,71L,1L,"TRAINING_RECORD_PDF/4",null)));}
 @Test void issuanceCapturesActualEmployeeAndPersistedDeadline(){SecurityFrameworkUtils.setLoginUser(new cn.iocoder.yudao.framework.security.core.LoginUser().setId(11L).setTenantId(7L),new org.springframework.mock.web.MockHttpServletRequest());allow(11);when(grants.selectLatestIssuance(any())).thenReturn(2L);when(grants.insert(any(TrainingConfirmationGrantDO.class))).thenAnswer(call->{((TrainingConfirmationGrantDO)call.getArgument(0)).setId(72L);return 1;});var created=service.createForIssue(9L,row.getSignTokenDigest());assertEquals(11L,created.getIssuedByUserId());assertEquals(3L,created.getIssuanceVersion());assertEquals(row.getTokenExpiresAt(),created.getExpiresAt());assertEquals(row.getSignTokenDigest(),created.getTokenDigest());verify(grants,never()).updateById(any(TrainingConfirmationGrantDO.class));}
 @Test void lossOfCurrentGrantCannotDowngradeNewIssuanceToLegacyPath(){when(grants.selectCurrentGrant(any())).thenReturn(null);when(grants.selectLatestIssuance(any())).thenReturn(1L);assertThrows(Exception.class,()->service.findForConfirmation(row));verifyNoInteractions(permissions);}
 @Test void genuinelyHistoricalRootWithoutIssuanceEvidenceRetainsLegacyPath(){when(grants.selectCurrentGrant(any())).thenReturn(null);when(grants.selectLatestIssuance(any())).thenReturn(null);assertNull(service.findForConfirmation(row));verify(grants).selectLatestIssuance(new TrainingGrantIssuanceQuery(7L,9L));}

}
